name = "pic"
version = "0.1.0"
license = "MIT"
author = "JorgeG94"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2024, JorgeG94"
[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]
[library]
source-dir = "src"
[build]
#auto-executables = true
auto-tests = false
#auto-examples = true
module-naming = false
external-modules = ["mpi_f08"]
[[test]]
name = "pic"
source-dir = "test"
main = "main_tests.f90"
[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
#stdlib="*"
test-drive.git = "https://github.com/fortran-lang/test-drive"
#openmp = "*"
#blas= "*"
#mpi = "*"
jonquil.git = "https://github.com/toml-f/jonquil"
[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["C003", "C072"]
line-length = 132
per-file-ignores = { "pic_blas_interfaces.F90" = ["C071"] }
