name = "pic"
version = "0.0.1"
license = "MIT"
author = "JorgeG94"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2024, JorgeG94"
description = "A collection of commonly used features implemented in Fortran with portability in mind"
homepage = "https://jorgeg94.github.io/pic/"

[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]

[library]
source-dir = "src"
type = "static"
[build]
auto-tests = false
module-naming = false
external-modules = ["mpi_f08"]
[[test]]
name = "pic"
source-dir = "test"
main = "main_tests.f90"

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
test-drive.git = "https://github.com/JorgeG94/test-drive"
#jonquil.git = "https://github.com/toml-f/jonquil"

[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["C003", "C072"]
line-length = 132
per-file-ignores = { "pic_blas_interfaces.F90" = ["C071"] }
