int32_ord_sort – PIC
int32_ord_sort Module Subroutine
10 statements
Source File
private module subroutine int32_ord_sort(array, work, reverse)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: array(0:)
integer(kind=int32), intent(out), optional :: work(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      module subroutine int32_ord_sort(array, work, reverse)
         implicit none
!! `int32_ord_sort(array)` sorts the input `ARRAY` of type `integer(int32)`
!! using a hybrid sort based on the `"Rust" sort` algorithm found in `slice.rs`
         integer(int32), intent(inout)         :: array(0:)
         integer(int32), intent(out), optional :: work(0:)
         logical, intent(in), optional :: reverse
      end subroutine int32_ord_sort
Call graph
int32_ord_sort calls pic_optional, int32_decrease_ord_sort, int32_increase_ord_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
int32_decrease_ord_sort calls merge_sort
int32_increase_ord_sort calls merge_sort