is_sorted_int64 – PIC
is_sorted_int64 Function
25 statements
Source File
private pure function is_sorted_int64(array, order) result(sorted)
check if a 1d array of type int64 is sorted
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
integer(kind=default_int), private :: sort_order
Source Code
   pure function is_sorted_int64(array, order) result(sorted)
        !! check if a 1d array of type int64 is sorted
      integer(int64), intent(in) :: array(:)
      integer(default_int), intent(in), optional :: order
      integer(default_int):: sort_order
      integer(default_int) :: i
      logical :: sorted
      sorted = .true.
      sort_order = pic_optional(order, ASCENDING)
      select case (sort_order)
      case (DESCENDING)
         do i = 1, size(array) - 1
            if (array(i + 1) > array(i)) then
               sorted = .false.
               return
            end if
         end do
      case default  ! ASCENDING or any other value
         do i = 1, size(array) - 1
            if (array(i + 1) < array(i)) then
               sorted = .false.
               return
            end if
         end do
      end select
   end function is_sorted_int64
Call graph
is_sorted_int64 calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
is_sorted calls is_sorted_int64