padl_char_pad_with – PIC
padl_char_pad_with Function
14 statements
Source File
private pure function padl_char_pad_with(string, output_length, pad_with) result(res)
Left pad the input string with the ‘pad_with’ character
Returns a new string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: output_length
character(len=1), intent(in) :: pad_with
Return Value character(kind=output_length), len=max)
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: string_length
Source Code
   pure function padl_char_pad_with(string, output_length, pad_with) result(res)
      character(len=*), intent(in) :: string
      integer, intent(in) :: output_length
      character(len=1), intent(in) :: pad_with
      character(len=max(len(string), output_length)) :: res
      integer :: string_length
      string_length = len(string)
      if (string_length < output_length) then
         res = repeat(pad_with, output_length - string_length)
         res(output_length - string_length + 1:output_length) = string
      else
         res = string
      end if
   end function padl_char_pad_with
Call graph
padl calls padl_char_pad_with, padl_char_default, padl_string_default, padl_string_pad_with
padl_char_default calls padl
padl_string_default calls padl
padl_string_pad_with calls padl
zfill_char calls padl
zfill_string calls padl
zfill calls zfill_char, zfill_string