set_brackets – PIC
set_brackets Subroutine
19 statements
Source File
private subroutine set_brackets(format_type, open_bracket, close_bracket)
Set brackets based on output format type
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: format_type
character(len=1), intent(out) :: open_bracket
character(len=1), intent(out) :: close_bracket
Calls
Called by
Source Code
   subroutine set_brackets(format_type, open_bracket, close_bracket)
   !! Set brackets based on output format type
      character(len=*), intent(in) :: format_type
      character(len=1), intent(out) :: open_bracket, close_bracket
      select case (trim(to_upper(adjustl(format_type))))
      case ("NUMPY")
         open_bracket = "["
         close_bracket = "]"
      case ("MATHEMATICA")
         open_bracket = "{"
         close_bracket = "}"
      case ("PLAIN")
         open_bracket = "["
         close_bracket = "]"
      case default
         print *, "Warning: Unsupported format type '"//trim(format_type)//"'. Defaulting to NumPy style."
         open_bracket = "["
         close_bracket = "]"
      end select
   end subroutine set_brackets
Call graph
set_brackets calls to_upper
print_3d_tensor_dp calls set_brackets, pic_print_array
print_3d_tensor_int32 calls set_brackets, pic_print_array
print_3d_tensor_int64 calls set_brackets, pic_print_array
print_3d_tensor_sp calls set_brackets, pic_print_array
print_matrix_dp calls set_brackets
print_matrix_int32 calls set_brackets
print_matrix_int64 calls set_brackets
print_matrix_sp calls set_brackets
print_packed_matrix_dp calls set_brackets
print_packed_matrix_int32 calls set_brackets
print_packed_matrix_int64 calls set_brackets
print_packed_matrix_sp calls set_brackets
print_vector_dp calls set_brackets
print_vector_int32 calls set_brackets
print_vector_int64 calls set_brackets
print_vector_sp calls set_brackets
pic_print_array calls print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp, print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp