sp_ord_sort – PIC
sp_ord_sort Module Subroutine
10 statements
Source File
private module subroutine sp_ord_sort(array, work, reverse)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: array(0:)
real(kind=sp), intent(out), optional :: work(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      module subroutine sp_ord_sort(array, work, reverse)
         implicit none
!! `sp_ord_sort(array)` sorts the input `ARRAY` of type `real(sp)`
!! using a hybrid sort based on the `"Rust" sort` algorithm found in `slice.rs`
         real(sp), intent(inout)         :: array(0:)
         real(sp), intent(out), optional :: work(0:)
         logical, intent(in), optional :: reverse
      end subroutine sp_ord_sort
Call graph
sp_ord_sort calls pic_optional, sp_decrease_ord_sort, sp_increase_ord_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
sp_decrease_ord_sort calls merge_sort
sp_increase_ord_sort calls merge_sort