starts_with_string_string – PIC
starts_with_string_string Function
6 statements
Source File
private elemental function starts_with_string_string(string, substring) result(match)
Check whether a string starts with substring or not
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value logical
Calls
Called by
Source Code
   elemental function starts_with_string_string(string, substring) result(match)
      type(string_type), intent(in) :: string
      type(string_type), intent(in) :: substring
      logical :: match
      match = starts_with(char(string), char(substring))
   end function starts_with_string_string
Call graph
starts_with_string_string calls starts_with
starts_with calls starts_with_string_string, starts_with_char_char, starts_with_char_string, starts_with_string_char
starts_with_char_string calls starts_with
starts_with_string_char calls starts_with