#!/usr/bin/env python3
"""Generate the inverse-CDF table for pic_random_dist's integer exponential.

Emits `tools/autogen/pic_exp_table.inc`, an include file of
`integer(int64), parameter` values holding

    T(k) = -ln(1 - k/4096)   for k = 0 .. 4095

in Q32.32 fixed point, that is round(T(k) * 2**32).

The values are computed with `decimal` at 60 significant digits and then
rounded once, half away from zero, to the Q32.32 grid. Sixty digits is far
more than the ~20 needed to place a Q32.32 value unambiguously, so the output
is a deterministic function of the definition above and does not depend on
this machine's floating point.

The table has no explicit tail entry. T(4095) is ln(4096), and a draw landing
in the top cell is handled by the sampler with the memoryless property rather
than by interpolating into a capped final value -- see pic_random_dist.

Run from tools/autogen:  python3 gen_exp_table.py
"""
from decimal import Decimal, getcontext, ROUND_HALF_UP

getcontext().prec = 60

CELLS = 4096
SCALE = Decimal(2) ** 32
PER_LINE = 4
OUT = "pic_exp_table.inc"


def q32_32(value: Decimal) -> int:
    """Round a Decimal onto the Q32.32 grid, half away from zero."""
    return int((value * SCALE).to_integral_value(rounding=ROUND_HALF_UP))


def table() -> list[int]:
    one = Decimal(1)
    return [q32_32(-(one - Decimal(k) / CELLS).ln()) for k in range(CELLS)]


def main() -> None:
    values = table()

    assert values[0] == 0, "T(0) must be exactly zero"
    assert values == sorted(values), "the inverse CDF must be non-decreasing"
    assert values[CELLS - 1] == q32_32(Decimal(CELLS).ln()), "T(4095) must be ln(4096)"

    # The sampler interpolates inside a cell as `gap * frac31 >> 31`, in one
    # signed int64 multiply with no splitting. That is only safe while every
    # gap stays below 2**32: the widest possible product is then
    # (2**32 - 1) * (2**31 - 1) = 9223372030412324865, which is below
    # huge(int64) = 9223372036854775807. Assert it here rather than trusting
    # the reader to re-derive it.
    gaps = [values[k + 1] - values[k] for k in range(CELLS - 1)]
    widest = max(gaps)
    assert widest < 2 ** 32, f"cell gap {widest} would overflow the interpolation multiply"

    lines = [
        "! Generated by tools/autogen/gen_exp_table.py -- do not edit.",
        "!",
        f"! T(k) = -ln(1 - k/{CELLS}) in Q32.32 fixed point, k = 0 .. {CELLS - 1}.",
        "! The bound is spelled EXP_TOP_CELL, which the including module declares",
        "! just above; a bare 4095 here is a magic number the linter rejects.",
        "",
        "   integer(int64), parameter :: EXP_TABLE(0:EXP_TOP_CELL) = [ &",
    ]
    for start in range(0, CELLS, PER_LINE):
        chunk = values[start:start + PER_LINE]
        body = ", ".join(f"{v}_int64" for v in chunk)
        tail = ", &" if start + PER_LINE < CELLS else "]"
        lines.append(f"      {body}{tail}")

    with open(OUT, "w") as handle:
        handle.write("\n".join(lines) + "\n")

    print(f"{OUT}: {CELLS} entries, T(4095) = {values[-1]}_int64 (ln 4096)")
    print(f"  widest cell gap {widest} < 2**32 = {2 ** 32}, "
          f"headroom {2 ** 32 - widest}")


if __name__ == "__main__":
    main()
