operator(<) – PIC
operator(<) Interface
5 statements
Source File
public interface operator(<)
Compare two character sequences for being less, the left-hand side, the right-hand side or both character sequences can be represented by a string.
This operator is elemental and returns a default logical scalar value.
Calls
Module Procedures
private elemental function lt_string_string(lhs, rhs) result(is_lt)
Compare two character sequences for being less. In this version both character sequences are by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: lhs
type(string_type), intent(in) :: rhs
Return Value logical
private elemental function lt_string_char(lhs, rhs) result(is_lt)
Compare two character sequences for being less. In this version the left-hand side character sequences is by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: lhs
character(len=*), intent(in) :: rhs
Return Value logical
private elemental function lt_char_string(lhs, rhs) result(is_lt)
Compare two character sequences for being less. In this version the right-hand side character sequences is by a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: lhs
type(string_type), intent(in) :: rhs
Return Value logical
Call graph
operator(lt) calls lt_char_string, lt_string_char, lt_string_string