padr – PIC
padr Interface
experimental
6 statements
Source File
public interface padr
Right pad the input string
Calls
Called by
Module Procedures
private pure function padr_string_default(string, output_length) result(res)
Right pad the input string with ” ” (1 whitespace)
Read more…
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
Return Value type(string_type)
private pure function padr_string_pad_with(string, output_length, pad_with) result(res)
Right pad the input string with the ‘pad_with’ character
Read more…
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
character(len=1), intent(in) :: pad_with
Return Value type(string_type)
private pure function padr_char_default(string, output_length) result(res)
Right pad the input string with ” ” (1 whitespace)
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: output_length
Return Value character(kind=output_length), len=max)
private pure function padr_char_pad_with(string, output_length, pad_with) result(res)
Right pad the input string with the ‘pad_with’ character
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: output_length
character(len=1), intent(in) :: pad_with
Return Value character(kind=output_length), len=max)
Call graph
padr calls padr_char_default, padr_char_pad_with, padr_string_default, padr_string_pad_with
padr_string_pad_with calls padr