to_c_char – PIC
to_c_char Interface
experimental
4 statements
Source File
public interface to_c_char
Format or transfer other types as a string.
Calls
Module Procedures
private pure function to_c_char_from_char(value) result(cstr)
Convert a Fortran character string to a C character array
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: value
Return Value character(kind=c_char, len=1), (len(value)+1)
private pure function to_c_char_from_string(value) result(cstr)
Convert a Fortran string type to a C character array
Read more…
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: value
Return Value character(kind=c_char, len=1), (slen(value)+1)
Call graph
to_c_char calls to_c_char_from_char, to_c_char_from_string
to_c_char_from_string calls slen
slen calls len_string