char_sort_index_default – PIC
char_sort_index_default Module Subroutine
268 statements
Source File
private module subroutine char_sort_index_default(array, index, work, iwork, reverse)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(out) :: index(0:)
character(len=len), intent(out), optional :: work(0:)
integer(kind=int_index), intent(out), optional :: iwork(0:)
logical, intent(in), optional :: reverse
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int_index), private :: array_size
integer(kind=int_index), private :: i
integer(kind=int_index), private, allocatable :: ibuf(:)
integer(kind=int_index), private :: stat
Functions
pure function calc_min_run(n) result(min_run)
Returns the minimum length of a run from 32-63 so that N/MIN_RUN is less than or equal to a power of two. See https://svn.python.org/projects/python/trunk/Objects/listsort.txt
Arguments
Type Intent Optional Attributes Name
integer(kind=int_index), intent(in) :: n
Return Value integer(kind=int_index)
pure function collapse(runs) result(r)
Arguments
Type Intent Optional Attributes Name
type(run_type), intent(in), target :: runs(0:)
Return Value integer(kind=int_index)
Subroutines
pure subroutine insert_head(array, index)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(inout) :: index(0:)
pure subroutine insertion_sort(array, index)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(inout) :: index(0:)
pure subroutine merge(array, mid, buf, index, ibuf)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(in) :: mid
character(len=len), intent(inout) :: buf(0:)
integer(kind=int_index), intent(inout) :: index(0:)
integer(kind=int_index), intent(inout) :: ibuf(0:)
subroutine merge_sort(array, index, buf, ibuf)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(inout) :: index(0:)
character(len=len), intent(inout) :: buf(0:)
integer(kind=int_index), intent(inout) :: ibuf(0:)
pure subroutine reverse_segment(array, index)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
integer(kind=int_index), intent(inout) :: index(0:)
Source Code
      module subroutine char_sort_index_default(array, index, work, iwork, &
                                                reverse)
!! `char_sort_index_default(array, index[, work, iwork, reverse])` sorts
!! an input `ARRAY` of type `character(len=*)`
!! using a hybrid sort based on the `"Rust" sort` algorithm found in `slice.rs`
!! and returns the sorted `ARRAY` and an array `INDEX` of indices in the
!! order that would sort the input `ARRAY` in the desired direction.
         implicit none
         character(len=*), intent(inout)                     :: array(0:)
         integer(int_index), intent(out)                      :: index(0:)
         character(len=len(array)), intent(out), optional             :: work(0:)
         integer(int_index), intent(out), optional            :: iwork(0:)
         logical, intent(in), optional             :: reverse
      end subroutine char_sort_index_default
Call graph
char_sort_index_default calls pic_optional, merge_sort, reverse_segment
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp