char_ord_sort – PIC
char_ord_sort Module Subroutine
10 statements
Source File
private module subroutine char_ord_sort(array, work, reverse)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
character(len=len), intent(out), optional :: work(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      module subroutine char_ord_sort(array, work, reverse)
         implicit none
!! `char_ord_sort(array)` sorts the input `ARRAY` of type `character(len=*)`
!! using a hybrid sort based on the `"Rust" sort` algorithm found in `slice.rs`
         character(len=*), intent(inout)         :: array(0:)
         character(len=len(array)), intent(out), optional :: work(0:)
         logical, intent(in), optional :: reverse
      end subroutine char_ord_sort
Call graph
char_ord_sort calls pic_optional, char_decrease_ord_sort, char_increase_ord_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
char_decrease_ord_sort calls merge_sort
char_increase_ord_sort calls merge_sort