char_sort – PIC
char_sort Module Subroutine
9 statements
Source File
private pure module subroutine char_sort(array, reverse)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      pure module subroutine char_sort(array, reverse)
!! `char_sort(array[, reverse])` sorts the input `ARRAY` of type `character(len=*)`
!! using a hybrid sort based on the `introsort` of David Musser.
!! The algorithm is of order O(N Ln(N)) for all inputs.
!! Because it relies on `quicksort`, the coefficient of the O(N Ln(N))
!! behavior is small for random data compared to other sorting algorithms.
         implicit none
         character(len=*), intent(inout)         :: array(0:)
         logical, intent(in), optional :: reverse
      end subroutine char_sort
Call graph
char_sort calls pic_optional, char_decrease_sort, char_increase_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
char_decrease_sort calls introsort
char_increase_sort calls introsort