chomp_substring_string_string – PIC
chomp_substring_string_string Function
7 statements
Source File
private pure function chomp_substring_string_string(string, substring) result(chomped_string)
Uses
pic_string_type
Remove trailing substrings from string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value type(string_type)
Calls
Called by
Source Code
   pure function chomp_substring_string_string(string, substring) result(chomped_string)
      ! Avoid polluting the module scope and use the assignment only in this scope
      use pic_string_type, only: assignment(=)
      type(string_type), intent(in) :: string
      type(string_type), intent(in) :: substring
      type(string_type) :: chomped_string
      chomped_string = chomp(char(string), char(substring))
   end function chomp_substring_string_string
Call graph
chomp_substring_string_string calls chomp
chomp calls chomp_substring_string_string, chomp_char, chomp_set_char_char, chomp_set_string_char, chomp_string, chomp_substring_char_char, chomp_substring_char_string, chomp_substring_string_char
chomp_set_char_char calls set_to_string
chomp_set_string_char calls chomp
chomp_substring_char_string calls chomp
chomp_substring_string_char calls chomp