chomp_substring_char_string – PIC
chomp_substring_char_string Function
6 statements
Source File
private pure function chomp_substring_char_string(string, substring) result(chomped_string)
Remove trailing substrings from string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   pure function chomp_substring_char_string(string, substring) result(chomped_string)
      character(len=*), intent(in) :: string
      type(string_type), intent(in) :: substring
      character(len=:), allocatable :: chomped_string
      chomped_string = chomp(string, char(substring))
   end function chomp_substring_char_string
Call graph
chomp_substring_char_string calls chomp
chomp calls chomp_substring_char_string, chomp_char, chomp_set_char_char, chomp_set_string_char, chomp_string, chomp_substring_char_char, chomp_substring_string_char, chomp_substring_string_string
chomp_set_char_char calls set_to_string
chomp_set_string_char calls chomp
chomp_substring_string_char calls chomp
chomp_substring_string_string calls chomp