chomp_set_string_char – PIC
chomp_set_string_char Function
7 statements
Source File
private pure function chomp_set_string_char(string, set) result(chomped_string)
Uses
pic_string_type
Remove trailing characters in set from string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=1), intent(in) :: set(:)
Return Value type(string_type)
Calls
Called by
Source Code
   pure function chomp_set_string_char(string, set) result(chomped_string)
      ! Avoid polluting the module scope and use the assignment only in this scope
      use pic_string_type, only: assignment(=)
      type(string_type), intent(in) :: string
      character(len=1), intent(in) :: set(:)
      type(string_type) :: chomped_string
      chomped_string = chomp(char(string), set)
   end function chomp_set_string_char
Call graph
chomp_set_string_char calls chomp
chomp calls chomp_set_string_char, chomp_char, chomp_set_char_char, chomp_string, chomp_substring_char_char, chomp_substring_char_string, chomp_substring_string_char, chomp_substring_string_string
chomp_set_char_char calls set_to_string
chomp_substring_char_string calls chomp
chomp_substring_string_char calls chomp
chomp_substring_string_string calls chomp