compute_lps – PIC
compute_lps Function
23 statements
Source File
private pure function compute_lps(string) result(lps_array)
Computes longest prefix suffix for each index of the input ‘string’
Returns an array of integers
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value integer, (len(string))
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: j
integer, private :: length_string
Source Code
   pure function compute_lps(string) result(lps_array)
      character(len=*), intent(in) :: string
      integer :: lps_array(len(string))
      integer :: i, j, length_string
      length_string = len(string)
      if (length_string > 0) then
         lps_array(1) = 0
         i = 2
         j = 1
         do while (i <= length_string)
            if (string(j:j) == string(i:i)) then
               lps_array(i) = j
               i = i + 1
               j = j + 1
            else if (j > 1) then
               j = lps_array(j - 1) + 1
            else
               lps_array(i) = 0
               i = i + 1
            end if
         end do
      end if
   end function compute_lps
Call graph
count_char_char calls compute_lps
find_char_char calls compute_lps
replace_all_char_char_char calls compute_lps
count calls count_char_char
find calls find_char_char, find_char_string, find_string_char, find_string_string
replace_all calls replace_all_char_char_char, replace_all_char_char_string, replace_all_char_string_char, replace_all_char_string_string, replace_all_string_char_char, replace_all_string_char_string, replace_all_string_string_char, replace_all_string_string_string
find_char_string calls find
find_string_char calls find
find_string_string calls find
replace_all_char_char_string calls replace_all
replace_all_char_string_char calls replace_all
replace_all_char_string_string calls replace_all
replace_all_string_char_char calls replace_all
replace_all_string_char_string calls replace_all
replace_all_string_string_char calls replace_all
replace_all_string_string_string calls replace_all