copy_vector_int32 – PIC
copy_vector_int32 Subroutine
18 statements
Source File
private subroutine copy_vector_int32(dest, source, threaded)
copy a vector of datatype int32
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: dest(:)
integer(kind=int32), intent(in) :: source(:)
logical, intent(in), optional :: threaded
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
logical, private :: use_threads
Source Code
   subroutine copy_vector_int32(dest, source, threaded)
        !! copy a vector of datatype int32
      integer(int32), intent(inout) :: dest(:)
      integer(int32), intent(in)    :: source(:)
      logical, intent(in), optional :: threaded
      logical :: use_threads
      integer(default_int) :: i
      if (size(dest, 1) /= size(source, 1)) then
         error stop "Vector size mismatch"
      end if
      use_threads = pic_optional(threaded, use_threaded_default)
      if (use_threads) then
         !$omp parallel do collapse(1) private(i)
         do i = 1, size(dest, 1)
            dest(i) = source(i)
         end do
         !$omp end parallel do
      else
         dest = source
      end if
   end subroutine copy_vector_int32
Call graph
copy_vector_int32 calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
pic_copy calls copy_vector_int32