dp_ord_sort – PIC
dp_ord_sort Module Subroutine
10 statements
Source File
private module subroutine dp_ord_sort(array, work, reverse)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array(0:)
real(kind=dp), intent(out), optional :: work(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      module subroutine dp_ord_sort(array, work, reverse)
         implicit none
!! `dp_ord_sort(array)` sorts the input `ARRAY` of type `real(dp)`
!! using a hybrid sort based on the `"Rust" sort` algorithm found in `slice.rs`
         real(dp), intent(inout)         :: array(0:)
         real(dp), intent(out), optional :: work(0:)
         logical, intent(in), optional :: reverse
      end subroutine dp_ord_sort
Call graph
dp_ord_sort calls pic_optional, dp_decrease_ord_sort, dp_increase_ord_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
dp_decrease_ord_sort calls merge_sort
dp_increase_ord_sort calls merge_sort