dp_radix_sort – PIC
dp_radix_sort Module Subroutine
45 statements
Source File
private module subroutine dp_radix_sort(array, work, reverse)
Uses
iso_c_binding
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(:), target :: array
real(kind=dp), intent(inout), optional, dimension(:), target :: work
logical, intent(in), optional :: reverse
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int_index), private :: N
integer(kind=int64), private, dimension(:), pointer :: arri64
integer(kind=int64), private, dimension(:), pointer :: buffer
integer(kind=int_index), private :: i
real(kind=dp), private :: item
integer(kind=int_index), private :: pos
integer(kind=int_index), private :: rev_pos
logical, private :: use_internal_buffer
Source Code
      module subroutine dp_radix_sort(array, work, reverse)
         implicit none
         real(kind=dp), dimension(:), intent(inout), target :: array
         real(kind=dp), dimension(:), intent(inout), target, optional :: work
         logical, intent(in), optional :: reverse
      end subroutine dp_radix_sort
Call graph
dp_radix_sort calls pic_optional, radix_sort_u64_helper
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp