dp_sort – PIC
dp_sort Module Subroutine
9 statements
Source File
private pure module subroutine dp_sort(array, reverse)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      pure module subroutine dp_sort(array, reverse)
!! `dp_sort(array[, reverse])` sorts the input `ARRAY` of type `real(dp)`
!! using a hybrid sort based on the `introsort` of David Musser.
!! The algorithm is of order O(N Ln(N)) for all inputs.
!! Because it relies on `quicksort`, the coefficient of the O(N Ln(N))
!! behavior is small for random data compared to other sorting algorithms.
         implicit none
         real(dp), intent(inout)         :: array(0:)
         logical, intent(in), optional :: reverse
      end subroutine dp_sort
Call graph
dp_sort calls pic_optional, dp_decrease_sort, dp_increase_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
dp_decrease_sort calls introsort
dp_increase_sort calls introsort