ends_with_string_string – PIC
ends_with_string_string Function
6 statements
Source File
private elemental function ends_with_string_string(string, substring) result(match)
Check whether a string ends with substring or not
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: substring
Return Value logical
Calls
Called by
Source Code
   elemental function ends_with_string_string(string, substring) result(match)
      type(string_type), intent(in) :: string
      type(string_type), intent(in) :: substring
      logical :: match
      match = ends_with(char(string), char(substring))
   end function ends_with_string_string
Call graph
ends_with_string_string calls ends_with
ends_with calls ends_with_string_string, ends_with_char_char, ends_with_char_string, ends_with_string_char
ends_with_char_string calls ends_with
ends_with_string_char calls ends_with