ensure_capacity – PIC
ensure_capacity Subroutine
19 statements
Source File
private subroutine ensure_capacity(self, need)
helper routine to ensure that the string container has enough capacity to hold a new size ‘need’
Arguments
Type Intent Optional Attributes Name
class(pic_string_type), intent(inout) :: self
integer(kind=int64), intent(in) :: need
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), private :: target
character(len=:), private, allocatable :: tmp
Source Code
   subroutine ensure_capacity(self, need)
      !! helper routine to ensure that the string container has enough
      !! capacity to hold a new size 'need'
      class(pic_string_type), intent(inout) :: self
      integer(int64), intent(in)    :: need
      integer(int64) :: target
      character(len=:), allocatable :: tmp
      if (need <= self%cap) return
      if (self%cap <= 0_int64) then
         target = max(need, 64_int64)
      else
         target = self%cap
         do while (target < need)
            target = 2_int64*target
         end do
      end if
      allocate (character(len=target) :: tmp)
      if (self%len > 0 .and. allocated(self%buf)) tmp(1:self%len) = self%buf(1:self%len)
      call move_alloc(tmp, self%buf)
      self%cap = target
   end subroutine ensure_capacity
Call graph
pic_string_append calls ensure_capacity
pic_string_assign calls ensure_capacity
pic_string_push_back calls ensure_capacity
pic_string_reserve calls ensure_capacity
pic_string_substr calls pic_string_reserve