fill_vector_dp – PIC
fill_vector_dp Subroutine
15 statements
Source File
private subroutine fill_vector_dp(vector, alpha, threaded)
fill a vector of datatype dp with a value
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: vector(:)
real(kind=dp), intent(in) :: alpha
logical, intent(in), optional :: threaded
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
logical, private :: use_threads
Source Code
   subroutine fill_vector_dp(vector, alpha, threaded)
        !! fill a vector of datatype dp with a value
      real(dp), intent(inout) :: vector(:)
      real(dp), intent(in)    :: alpha
      logical, intent(in), optional :: threaded
      logical :: use_threads
      integer(default_int) :: i
      use_threads = pic_optional(threaded, use_threaded_default)
      if (use_threads) then
         !$omp parallel do collapse(1) private(i)
         do i = 1, size(vector, 1)
            vector(i) = alpha
         end do
         !$omp end parallel do
      else
         vector = alpha
      end if
   end subroutine fill_vector_dp
Call graph
fill_vector_dp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
pic_fill calls fill_vector_dp