find_char_string – PIC
find_char_string Function
8 statements
Source File
private elemental function find_char_string(string, pattern, occurrence, consider_overlapping) result(res)
Returns the starting index of the ‘occurrence’th occurrence of substring ‘pattern’ in input ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: pattern
integer, intent(in), optional :: occurrence
logical, intent(in), optional :: consider_overlapping
Return Value integer
Calls
Called by
Source Code
   elemental function find_char_string(string, pattern, occurrence, consider_overlapping) result(res)
      character(len=*), intent(in) :: string
      type(string_type), intent(in) :: pattern
      integer, intent(in), optional :: occurrence
      logical, intent(in), optional :: consider_overlapping
      integer :: res
      res = find(string, char(pattern), occurrence, consider_overlapping)
   end function find_char_string
Call graph
find_char_string calls find
find calls find_char_string, find_char_char, find_string_char, find_string_string
find_char_char calls pic_optional, compute_lps
find_string_char calls find
find_string_string calls find
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp