flop_rate_get_flop_rate – PIC
flop_rate_get_flop_rate Function
17 statements
Source File
private function flop_rate_get_flop_rate(self) result(flop_rate)
get the flop rate in GFLOP/s, return 0.0 if time is zero or negative
Type Bound
flop_rate_type
Arguments
Type Intent Optional Attributes Name
class(flop_rate_type), intent(inout) :: self
Return Value real(kind=dp)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), private :: flops
real(kind=dp), private :: time
Source Code
   function flop_rate_get_flop_rate(self) result(flop_rate)
  !! get the flop rate in GFLOP/s, return 0.0 if time is zero or negative
      class(flop_rate_type), intent(inout) :: self
      real(dp) :: flop_rate
      real(dp) :: time
      integer(int64) :: flops
      flops = self%m_flops%get()
      time = self%m_timer%get_elapsed_time()
      if (time <= 0.0_dp) then
         print *, "Warning: Time is zero or negative, setting flop rate to zero."
         self%m_flop_rate = 0.0_dp
         flop_rate = 0.0_dp
         return
      else
         self%m_flop_rate = flops/time/1.0e9_dp
         flop_rate = self%m_flop_rate
      end if
   end function flop_rate_get_flop_rate
Call graph
flop_rate_get_flop_rate calls get_flops, timer_get_elapsed_time
flop_rate_report calls flop_rate_get_flop_rate