flop_rate_report – PIC
flop_rate_report Subroutine
5 statements
Source File
private subroutine flop_rate_report(self)
report the flop rate, this will print the flop rate in GFLOP/s
Usage: call my_flop_rate%report()
where my_flop_rate is an instance of flop_rate_type
Type Bound
flop_rate_type
Arguments
Type Intent Optional Attributes Name
class(flop_rate_type), intent(inout) :: self
Calls
Source Code
   subroutine flop_rate_report(self)
      !! report the flop rate, this will print the flop rate in GFLOP/s
      !!
      !! Usage: call my_flop_rate%report()
      !!
      !! where my_flop_rate is an instance of flop_rate_type
      !!
      class(flop_rate_type), intent(inout) :: self
      self%m_flop_rate = self%get_flop_rate()
      print *, "Flop rate is "//to_string(self%m_flop_rate)//" GFLOP/s"
   end subroutine flop_rate_report
Call graph
flop_rate_report calls to_string, flop_rate_get_flop_rate
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp
flop_rate_get_flop_rate calls get_flops, timer_get_elapsed_time