get_gpu_information – PIC
get_gpu_information Subroutine
5 statements
Source File
public subroutine get_gpu_information(self)
call my_device%get_gpu_informatio() style subroutine to populate the object
Type Bound
pic_device_type
Arguments
Type Intent Optional Attributes Name
class(pic_device_type), intent(inout) :: self
Calls
Source Code
   subroutine get_gpu_information(self)
    !! call my_device%get_gpu_informatio() style subroutine to populate the object
      class(pic_device_type), intent(inout) :: self
      call get_gpu_memory_info(self)
      call get_device_id(self)
   end subroutine get_gpu_information
Call graph
get_gpu_information calls get_device_id, get_gpu_memory_info
get_device_id calls gpugetdevice
get_gpu_memory_info calls gpugetmeminfo