get_flops – PIC
get_flops Function
5 statements
Source File
private function get_flops(self) result(flops)
Get the int64 number of FLOPs we currently have in the counter
Usage: flops = my_flop_recorder%get()
Type Bound
flop_recorder_type
Arguments
Type Intent Optional Attributes Name
class(flop_recorder_type), intent(in) :: self
Return Value integer(kind=int64)
Called by
Source Code
   function get_flops(self) result(flops)
    !! Get the int64 number of FLOPs we currently have in the counter
    !!
    !! Usage: flops = my_flop_recorder%get()
    !!
      class(flop_recorder_type), intent(in) :: self
      integer(int64) :: flops
      flops = self%flop_count
   end function get_flops
Call graph
flop_rate_get_flop_rate calls get_flops
flop_rate_get_flops calls get_flops
flop_rate_report calls flop_rate_get_flop_rate