index_string_char – PIC
index_string_char Function
7 statements
Source File
private elemental function index_string_char(string, substring, back) result(pos)
Position of a sequence of character within a character sequence. In this version the main character sequence is represented by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: substring
logical, intent(in), optional :: back
Return Value integer
Calls
Called by
Source Code
elemental function index_string_char(string, substring, back) result(pos)
   type(string_type), intent(in) :: string
   character(len=*), intent(in) :: substring
   logical, intent(in), optional :: back
   integer :: pos
   pos = index(maybe(string), substring, pic_optional(back, .false.))
end function index_string_char
Call graph
index_string_char calls pic_optional, maybe
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
index calls index_string_char