int32_radix_sort – PIC
int32_radix_sort Module Subroutine
48 statements
Source File
private pure module subroutine int32_radix_sort(array, work, reverse)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), dimension(:) :: array
integer(kind=int32), intent(inout), optional, dimension(:), target :: work
logical, intent(in), optional :: reverse
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int_index), private :: N
integer(kind=int32), private, dimension(:), pointer :: buffer
integer(kind=int_index), private :: end
integer(kind=int_index), private :: i
integer(kind=int32), private :: item
integer(kind=int_index), private :: middle
integer(kind=int_index), private :: start
logical, private :: use_internal_buffer
Source Code
      pure module subroutine int32_radix_sort(array, work, reverse)
         implicit none
         integer(kind=int32), dimension(:), intent(inout) :: array
         integer(kind=int32), dimension(:), intent(inout), target, optional :: work
         logical, intent(in), optional :: reverse
      end subroutine int32_radix_sort
Call graph
int32_radix_sort calls pic_optional, radix_sort_u32_helper
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp