int64_sort – PIC
int64_sort Module Subroutine
9 statements
Source File
private pure module subroutine int64_sort(array, reverse)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: array(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      pure module subroutine int64_sort(array, reverse)
!! `int64_sort(array[, reverse])` sorts the input `ARRAY` of type `integer(int64)`
!! using a hybrid sort based on the `introsort` of David Musser.
!! The algorithm is of order O(N Ln(N)) for all inputs.
!! Because it relies on `quicksort`, the coefficient of the O(N Ln(N))
!! behavior is small for random data compared to other sorting algorithms.
         implicit none
         integer(int64), intent(inout)         :: array(0:)
         logical, intent(in), optional :: reverse
      end subroutine int64_sort
Call graph
int64_sort calls pic_optional, int64_decrease_sort, int64_increase_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
int64_decrease_sort calls introsort
int64_increase_sort calls introsort