is_alphanum – PIC
is_alphanum Function
4 statements
Source File
public elemental function is_alphanum(c)
Checks whether c is a letter or a number (0 .. 9, a .. z, A .. Z).
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
The character to test.
Return Value logical
Called by
Source Code
   elemental logical function is_alphanum(c)
      character(len=1), intent(in) :: c
          !! The character to test.
      is_alphanum = (c >= '0' .and. c <= '9') .or. (c >= 'a' .and. c <= 'z') &
                    .or. (c >= 'A' .and. c <= 'Z')
   end function is_alphanum
Call graph
is_punctuation calls is_alphanum
to_sentence calls is_alphanum
to_title calls is_alphanum