maybe – PIC
maybe Function
9 statements
Source File
private pure function maybe(string) result(maybe_string)
Safely return the character sequences represented by the string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
Return Value character(len=slen)
Called by
Source Code
pure function maybe(string) result(maybe_string)
   type(string_type), intent(in) :: string
   character(len=slen(string)) :: maybe_string
   if (allocated(string%raw)) then
      maybe_string = string%raw
   else
      maybe_string = ''
   end if
end function maybe
Call graph
adjustl_string calls maybe
adjustr_string calls maybe
char_string calls maybe
concat_char_string calls maybe
concat_string_char calls maybe
concat_string_string calls maybe
gt_char_string calls maybe
gt_string_char calls maybe
gt_string_string calls maybe
index_char_string calls maybe
index_string_char calls maybe
index_string_string calls maybe
lge_char_string calls maybe
lge_string_char calls maybe
lge_string_string calls maybe
lgt_char_string calls maybe
lgt_string_char calls maybe
lgt_string_string calls maybe
lle_char_string calls maybe
lle_string_char calls maybe
lle_string_string calls maybe
llt_char_string calls maybe
llt_string_char calls maybe
llt_string_string calls maybe
repeat_string calls maybe
reverse_string calls maybe
scan_char_string calls maybe
scan_string_char calls maybe
scan_string_string calls maybe
to_lower_string calls maybe
to_sentence_string calls maybe
to_title_string calls maybe
to_upper_string calls maybe
trim_string calls maybe
verify_char_string calls maybe
verify_string_char calls maybe
verify_string_string calls maybe
write_formatted calls maybe
write_unformatted calls maybe
adjustl calls adjustl_string
adjustr calls adjustr_string
char calls char_string
index calls index_char_string, index_string_char, index_string_string
lge calls lge_char_string, lge_string_char, lge_string_string
lgt calls lgt_char_string, lgt_string_char, lgt_string_string
lle calls lle_char_string, lle_string_char, lle_string_string
llt calls llt_char_string, llt_string_char, llt_string_string
operator(SLASHSLASH) calls concat_char_string, concat_string_char, concat_string_string
operator(gt) calls gt_char_string, gt_string_char, gt_string_string
repeat calls repeat_string
reverse calls reverse_string
scan calls scan_char_string, scan_string_char, scan_string_string
to_lower calls to_lower_string
to_sentence calls to_sentence_string
to_title calls to_title_string
to_upper calls to_upper_string
trim calls trim_string
verify calls verify_char_string, verify_string_char, verify_string_string
write (formatted) calls write_formatted
write (unformatted) calls write_unformatted