optional_int64 – PIC
optional_int64 Function
10 statements
Source File
private pure function optional_int64(input_value, default_value) result(output)
Handle optional integer(int64) value
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), optional :: input_value
integer(kind=int64), intent(in) :: default_value
Return Value integer(kind=int64)
Called by
Source Code
   pure function optional_int64(input_value, default_value) result(output)
      !! Handle optional integer(int64) value
      integer(int64), intent(in), optional :: input_value
      integer(int64), intent(in) :: default_value
      integer(int64) :: output
      if (present(input_value)) then
         output = input_value
      else
         output = default_value
      end if
   end function optional_int64
Call graph
pic_optional calls optional_int64
char_ord_sort calls pic_optional
char_sort calls pic_optional
char_sort_index_default calls pic_optional
char_sort_index_low calls pic_optional
copy_3d_tensor_dp calls pic_optional
copy_3d_tensor_int32 calls pic_optional
copy_3d_tensor_int64 calls pic_optional
copy_3d_tensor_sp calls pic_optional
copy_matrix_dp calls pic_optional
copy_matrix_int32 calls pic_optional
copy_matrix_int64 calls pic_optional
copy_matrix_sp calls pic_optional
copy_vector_dp calls pic_optional
copy_vector_int32 calls pic_optional
copy_vector_int64 calls pic_optional
copy_vector_sp calls pic_optional
count_char_char calls pic_optional
dp_ord_sort calls pic_optional
dp_radix_sort calls pic_optional
dp_sort calls pic_optional
dp_sort_index_default calls pic_optional
dp_sort_index_low calls pic_optional
fill_3d_tensor_dp calls pic_optional
fill_3d_tensor_int32 calls pic_optional
fill_3d_tensor_int64 calls pic_optional
fill_3d_tensor_sp calls pic_optional
fill_matrix_dp calls pic_optional
fill_matrix_int32 calls pic_optional
fill_matrix_int64 calls pic_optional
fill_matrix_sp calls pic_optional
fill_vector_dp calls pic_optional
fill_vector_int32 calls pic_optional
fill_vector_int64 calls pic_optional
fill_vector_sp calls pic_optional
find_char_char calls pic_optional
index_char_string calls pic_optional
index_string_char calls pic_optional
index_string_string calls pic_optional
int32_ord_sort calls pic_optional
int32_radix_sort calls pic_optional
int32_sort calls pic_optional
int32_sort_index_default calls pic_optional
int32_sort_index_low calls pic_optional
int64_ord_sort calls pic_optional
int64_radix_sort calls pic_optional
int64_sort calls pic_optional
int64_sort_index_default calls pic_optional
int64_sort_index_low calls pic_optional
is_sorted_char calls pic_optional
is_sorted_dp calls pic_optional
is_sorted_int32 calls pic_optional
is_sorted_int64 calls pic_optional
is_sorted_sp calls pic_optional
print_3d_tensor_dp calls pic_optional, pic_print_array
print_3d_tensor_int32 calls pic_optional, pic_print_array
print_3d_tensor_int64 calls pic_optional, pic_print_array
print_3d_tensor_sp calls pic_optional, pic_print_array
print_matrix_dp calls pic_optional
print_matrix_int32 calls pic_optional
print_matrix_int64 calls pic_optional
print_matrix_sp calls pic_optional
print_packed_matrix_dp calls pic_optional
print_packed_matrix_int32 calls pic_optional
print_packed_matrix_int64 calls pic_optional
print_packed_matrix_sp calls pic_optional
print_vector_dp calls pic_optional
print_vector_int32 calls pic_optional
print_vector_int64 calls pic_optional
print_vector_sp calls pic_optional
scan_char_string calls pic_optional
scan_string_char calls pic_optional
scan_string_string calls pic_optional
sp_ord_sort calls pic_optional
sp_radix_sort calls pic_optional
sp_sort calls pic_optional
sp_sort_index_default calls pic_optional
sp_sort_index_low calls pic_optional
sum_3d_tensor_dp calls pic_optional
sum_3d_tensor_int32 calls pic_optional
sum_3d_tensor_int64 calls pic_optional
sum_3d_tensor_sp calls pic_optional
sum_matrix_dp calls pic_optional
sum_matrix_int32 calls pic_optional
sum_matrix_int64 calls pic_optional
sum_matrix_sp calls pic_optional
sum_vector_dp calls pic_optional
sum_vector_int32 calls pic_optional
sum_vector_int64 calls pic_optional
sum_vector_sp calls pic_optional
to_string_r_dp calls pic_optional
to_string_r_sp calls pic_optional
transpose_matrix_dp calls pic_optional
transpose_matrix_int32 calls pic_optional
transpose_matrix_int64 calls pic_optional
transpose_matrix_sp calls pic_optional
verify_char_string calls pic_optional
verify_string_char calls pic_optional
verify_string_string calls pic_optional
count calls count_char_char
find calls find_char_char, find_char_string, find_string_char, find_string_string
index calls index_char_string, index_string_char, index_string_string
is_sorted calls is_sorted_char, is_sorted_dp, is_sorted_int32, is_sorted_int64, is_sorted_sp
pic_copy calls copy_3d_tensor_dp, copy_3d_tensor_int32, copy_3d_tensor_int64, copy_3d_tensor_sp, copy_matrix_dp, copy_matrix_int32, copy_matrix_int64, copy_matrix_sp, copy_vector_dp, copy_vector_int32, copy_vector_int64, copy_vector_sp
pic_fill calls fill_3d_tensor_dp, fill_3d_tensor_int32, fill_3d_tensor_int64, fill_3d_tensor_sp, fill_matrix_dp, fill_matrix_int32, fill_matrix_int64, fill_matrix_sp, fill_vector_dp, fill_vector_int32, fill_vector_int64, fill_vector_sp
pic_print_array calls print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp, print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp
pic_sum calls sum_3d_tensor_dp, sum_3d_tensor_int32, sum_3d_tensor_int64, sum_3d_tensor_sp, sum_matrix_dp, sum_matrix_int32, sum_matrix_int64, sum_matrix_sp, sum_vector_dp, sum_vector_int32, sum_vector_int64, sum_vector_sp
pic_transpose calls transpose_matrix_dp, transpose_matrix_int32, transpose_matrix_int64, transpose_matrix_sp
scan calls scan_char_string, scan_string_char, scan_string_string
verify calls verify_char_string, verify_string_char, verify_string_string
find_char_string calls find
find_string_char calls find
find_string_string calls find