padl_string_default – PIC
padl_string_default Function
6 statements
Source File
private pure function padl_string_default(string, output_length) result(res)
Left pad the input string with ” ” (1 whitespace)
Returns a new string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
Return Value type(string_type)
Calls
Called by
Source Code
   pure function padl_string_default(string, output_length) result(res)
      type(string_type), intent(in) :: string
      integer, intent(in) :: output_length
      type(string_type) :: res
      res = string_type(padl(char(string), output_length, " "))
   end function padl_string_default
Call graph
padl_string_default calls padl
padl calls padl_string_default, padl_char_default, padl_char_pad_with, padl_string_pad_with
padl_char_default calls padl
padl_string_pad_with calls padl
zfill_char calls padl
zfill_string calls padl
zfill calls zfill_char, zfill_string