padl_string_pad_with – PIC
padl_string_pad_with Function
7 statements
Source File
private pure function padl_string_pad_with(string, output_length, pad_with) result(res)
Left pad the input string with the ‘pad_with’ character
Returns a new string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
character(len=1), intent(in) :: pad_with
Return Value type(string_type)
Calls
Called by
Source Code
   pure function padl_string_pad_with(string, output_length, pad_with) result(res)
      type(string_type), intent(in) :: string
      integer, intent(in) :: output_length
      character(len=1), intent(in) :: pad_with
      type(string_type) :: res
      res = string_type(padl(char(string), output_length, pad_with))
   end function padl_string_pad_with
Call graph
padl_string_pad_with calls padl
padl calls padl_string_pad_with, padl_char_default, padl_char_pad_with, padl_string_default
padl_char_default calls padl
padl_string_default calls padl
zfill_char calls padl
zfill_string calls padl
zfill calls zfill_char, zfill_string