pic_string_find – PIC
pic_string_find Function
25 statements
Source File
private pure function pic_string_find(self, pat, from) result(pos)
Uses
pic_optional_value
find the first occurrence of pattern ‘pat’ in the string
Type Bound
pic_string_type
Arguments
Type Intent Optional Attributes Name
class(pic_string_type), intent(in) :: self
character(len=*), intent(in) :: pat
integer(kind=int64), intent(in), optional :: from
Return Value integer(kind=int64)
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), private :: i0
integer(kind=int64), private :: j
integer(kind=int64), private :: j_end
integer(kind=int64), private :: m
integer(kind=int64), private :: nlen
character(len=:), private, allocatable :: s
Source Code
   pure integer(int64) function pic_string_find(self, pat, from) result(pos)
      !! find the first occurrence of pattern 'pat' in the string
      use pic_optional_value, only: pic_optional
      class(pic_string_type), intent(in) :: self
      character(*), intent(in) :: pat
      integer(int64), optional, intent(in):: from
      integer(int64) :: nlen, i0, j, j_end, m
      character(len=:), allocatable :: s
      pos = 0_int64
      nlen = self%len
      if (nlen == 0_int64) return
      m = int(len(pat), int64)
      if (m == 0_int64) return
      i0 = pic_optional(from, 1_int64)
      if (i0 < 1_int64 .or. i0 > nlen) return
      if (m > nlen - i0 + 1_int64) return
      allocate (character(len=nlen) :: s)
      s = self%buf(1:nlen)
      j_end = nlen - m + 1_int64
      do j = i0, j_end
         if (s(j:j + m - 1_int64) == pat) then
            pos = j
            return
         end if
      end do
   end function pic_string_find
Call graph
pic_string_find calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp