print_vector_int32 – PIC
print_vector_int32 Subroutine
25 statements
Source File
private subroutine print_vector_int32(vector, format_type)
print a vector of int32 values
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: vector(:)
character(len=*), intent(in), optional :: format_type
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=20), private :: print_format
Source Code
   subroutine print_vector_int32(vector, format_type)
 !! print a vector of int32 values
      integer(int32), intent(in) :: vector(:)
      character(len=*), intent(in), optional :: format_type
      character(len=20) :: print_format
      if (present(format_type)) then
         print_format = format_type
      else
         print_format = default_format
      end if
      print: block
         character(len=1) :: open_bracket, close_bracket
         integer(int32) :: i, loop_bound_i
         loop_bound_i = size(vector)
         call set_brackets(print_format, open_bracket, close_bracket)
         write (*, "(A)", advance="no") open_bracket
         do i = 1, loop_bound_i
            if (i == loop_bound_i) then  ! Last element in the vector
               write (*, fmt_edge, advance="no") to_string(vector(i))
            else  ! Elements in between
               write (*, fmt_in, advance="no") to_string(vector(i))
            end if
         end do
         print *, close_bracket
      end block print
   end subroutine print_vector_int32
Call graph
print_vector_int32 calls to_string, set_brackets
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_sp
print_array_v2 calls print_vector_int32, print_3d_tensor_dp, print_3d_tensor_sp
print_3d_tensor_dp calls print_array_v2
print_3d_tensor_sp calls print_array_v2