print_vector_n – PIC
print_vector_n Subroutine
16 statements
Source File
private subroutine print_vector_n(vec, n_elements, format_type)
print a vector from start up to n_elements
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vec(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=20), private :: format_selected
Source Code
   subroutine print_vector_n(vec, n_elements, format_type)
    !! print a vector from start up to n_elements
      real(dp), intent(in) :: vec(:)
      character(len=*), intent(in), optional :: format_type
      character(len=20) :: format_selected
      integer(kind=default_int), intent(in) :: n_elements
      ! Determine the format: default to "PLAIN" if not specified
      if (present(format_type)) then
         format_selected = trim(adjustl(format_type))
      else
         format_selected = "PLAIN"
      end if
      ! Handle plain format separately or delegate to print routine based on the format
      if (format_selected == "PLAIN") then
         call print_plain_vector(vec, n_elements)
      else
         call print_vector_in_format(vec, format_selected, n_elements)
      end if
   end subroutine print_vector_n
Call graph
print_vector_n calls print_plain_vector, print_vector_in_format
print_array_with_bounds calls print_vector_n