print_packed_matrix_int64 – PIC
print_packed_matrix_int64 Subroutine
36 statements
Source File
private subroutine print_packed_matrix_int64(packed, n_elements, format_type)
Print a packed lower triangular matrix of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: packed(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=1), private :: close_bracket
integer(kind=default_int), private :: i
integer(kind=default_int), private :: idx
integer(kind=default_int), private :: j
integer(kind=default_int), private :: n
real(kind=dp), private :: n_real
character(len=1), private :: open_bracket
character(len=20), private :: print_format
Source Code
   subroutine print_packed_matrix_int64(packed, n_elements, format_type)
   !! Print a packed lower triangular matrix of ${T} values
      integer(int64), intent(in) :: packed(:)
      integer(default_int), intent(in) :: n_elements
      character(len=*), intent(in), optional :: format_type
      character(len=20) :: print_format
      character(len=1) :: open_bracket, close_bracket
      integer(default_int) :: i, j, idx, n
      real(dp) :: n_real
      ! Determine format
      print_format = pic_optional(format_type, default_format)
      call set_brackets(print_format, open_bracket, close_bracket)
      ! Compute n from packed size using proper real arithmetic
      n_real = (-1.0_dp + sqrt(1.0_dp + 8.0_dp*real(n_elements, dp)))/2.0_dp
      n = int(n_real + 0.5_dp, default_int)
      if (n*(n + 1)/2 /= n_elements) then
         print *, "Error: n_elements does not form a valid packed triangle"
         return
      end if
      ! Print lower triangle directly from packed array
      print *, open_bracket
      idx = 0
      do i = 1, n
         write (*, '(A)', advance="no") open_bracket
         do j = 1, i
            idx = idx + 1
            if (j == i) then
               write (*, '(A)', advance="no") to_string(packed(idx))
            else
               write (*, '(A)', advance="no") trim(to_string(packed(idx))//", ")
            end if
         end do
         if (i == n) then
            print *, close_bracket
         else
            print *, close_bracket, ","
         end if
      end do
      print *, close_bracket
   end subroutine print_packed_matrix_int64
Call graph
print_packed_matrix_int64 calls pic_optional, to_string, set_brackets
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp
set_brackets calls to_upper
pic_print_array calls print_packed_matrix_int64, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp
print_3d_tensor_dp calls pic_print_array
print_3d_tensor_int32 calls pic_print_array
print_3d_tensor_int64 calls pic_print_array
print_3d_tensor_sp calls pic_print_array