print_plain_vector – PIC
print_plain_vector Subroutine
14 statements
Source File
private subroutine print_plain_vector(vec, n_elements)
private subroutine that prints a vector of n_elements
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vec(:)
integer(kind=default_int), intent(in), optional :: n_elements
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
integer(kind=default_int), private :: loop_bound
Source Code
   subroutine print_plain_vector(vec, n_elements)
    !! private subroutine that prints a vector of n_elements
      real(kind=dp), intent(in) :: vec(:)
      integer(kind=default_int), intent(in), optional :: n_elements
      integer(kind=default_int) :: i, loop_bound
      if (present(n_elements)) then
         loop_bound = n_elements
      else
         loop_bound = size(vec)
      end if
      print *, "Vector (Plain format):"
      do i = 1, loop_bound
         write (*, fmt_edge) vec(i)
      end do
   end subroutine print_plain_vector
Call graph
print_vector calls print_plain_vector
print_vector_n calls print_plain_vector
print_array calls print_vector
print_array_with_bounds calls print_vector_n