print_matrix_dp – PIC
print_matrix_dp Subroutine
30 statements
Source File
private subroutine print_matrix_dp(matrix, format_type)
print a matrix of values
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: matrix(:,:)
character(len=*), intent(in), optional :: format_type
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=20), private :: print_format
Source Code
   subroutine print_matrix_dp(matrix, format_type)
    !! print a matrix of ${T} values
      real(dp), intent(in) :: matrix(:, :)
      character(len=*), intent(in), optional :: format_type
      character(len=20) :: print_format
      print_format = pic_optional(format_type, default_format)
      print: block
         character(len=1) :: open_bracket, close_bracket
         integer(default_int) :: i, j, rows, cols
         rows = size(matrix, 1)
         cols = size(matrix, 2)
         call set_brackets(print_format, open_bracket, close_bracket)
         print *, open_bracket
         do i = 1, rows
            write (*, "(A)", advance="no") open_bracket
            do j = 1, cols
               if (j == cols) then  ! Last element in the row
                  write (*, fmt_edge, advance="no") to_string(matrix(i, j))
               else  ! Elements in between
                  write (*, fmt_in, advance="no") to_string(matrix(i, j))
               end if
            end do
            if (i == rows) then
               print *, close_bracket
            else
               print *, close_bracket, ","
            end if
         end do
         print *, close_bracket
      end block print
   end subroutine print_matrix_dp
Call graph
print_matrix_dp calls pic_optional, to_string, set_brackets
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp
set_brackets calls to_upper
pic_print_array calls print_matrix_dp, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp
print_3d_tensor_dp calls pic_print_array
print_3d_tensor_int32 calls pic_print_array
print_3d_tensor_int64 calls pic_print_array
print_3d_tensor_sp calls pic_print_array