print_3d_tensor_sp – PIC
print_3d_tensor_sp Subroutine
22 statements
Source File
private subroutine print_3d_tensor_sp(matrix, format_type)
Print a 3D tensor of values
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: matrix(:,:,:)
character(len=*), intent(in), optional :: format_type
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=20), private :: print_format
Source Code
   subroutine print_3d_tensor_sp(matrix, format_type)
    !! Print a 3D tensor of ${T} values
      real(sp), intent(in) :: matrix(:, :, :)
      character(len=*), intent(in), optional :: format_type
      character(len=20) :: print_format
      print_format = pic_optional(format_type, default_format)
      print: block
         character(len=1) :: open_bracket, close_bracket
         integer(int32) :: k, rows, cols, depth
         rows = size(matrix, 1)
         cols = size(matrix, 2)
         depth = size(matrix, 3)
         call set_brackets(print_format, open_bracket, close_bracket)
         print *, open_bracket
         do k = 1, depth
            if (k > 1) print *, ","
            print *, open_bracket
            call pic_print_array(matrix(:, :, k), print_format)
            print *, close_bracket
         end do
         print *, close_bracket
      end block print
   end subroutine print_3d_tensor_sp
Call graph
print_3d_tensor_sp calls pic_optional, pic_print_array, set_brackets
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
pic_print_array calls print_3d_tensor_sp, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp
set_brackets calls to_upper
print_3d_tensor_dp calls pic_optional, pic_print_array, set_brackets
print_3d_tensor_int32 calls pic_optional, pic_print_array, set_brackets
print_3d_tensor_int64 calls pic_optional, pic_print_array, set_brackets
print_matrix_dp calls pic_optional, set_brackets, to_string
print_matrix_int32 calls pic_optional, set_brackets, to_string
print_matrix_int64 calls pic_optional, set_brackets, to_string
print_matrix_sp calls pic_optional, set_brackets, to_string
print_packed_matrix_dp calls pic_optional, set_brackets, to_string
print_packed_matrix_int32 calls pic_optional, set_brackets, to_string
print_packed_matrix_int64 calls pic_optional, set_brackets, to_string
print_packed_matrix_sp calls pic_optional, set_brackets, to_string
print_vector_dp calls pic_optional, set_brackets, to_string
print_vector_int32 calls pic_optional, set_brackets, to_string
print_vector_int64 calls pic_optional, set_brackets, to_string
print_vector_sp calls pic_optional, set_brackets, to_string
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp