replace_all_string_string_string – PIC
replace_all_string_string_string Function
7 statements
Source File
private pure function replace_all_string_string_string(string, pattern, replacement) result(res)
Replaces all occurrences of substring ‘pattern’ in the input ‘string’ with the replacement ‘replacement’ Returns a new string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: pattern
type(string_type), intent(in) :: replacement
Return Value type(string_type)
Calls
Called by
Source Code
   pure function replace_all_string_string_string(string, pattern, replacement) result(res)
      type(string_type), intent(in) :: string
      type(string_type), intent(in) :: pattern
      type(string_type), intent(in) :: replacement
      type(string_type) :: res
      res = string_type(replace_all(char(string), &
              & char(pattern), char(replacement)))
   end function replace_all_string_string_string
Call graph
replace_all_string_string_string calls replace_all
replace_all calls replace_all_string_string_string, replace_all_char_char_char, replace_all_char_char_string, replace_all_char_string_char, replace_all_char_string_string, replace_all_string_char_char, replace_all_string_char_string, replace_all_string_string_char
replace_all_char_char_char calls compute_lps
replace_all_char_char_string calls replace_all
replace_all_char_string_char calls replace_all
replace_all_char_string_string calls replace_all
replace_all_string_char_char calls replace_all
replace_all_string_char_string calls replace_all
replace_all_string_string_char calls replace_all