sp_sort – PIC
sp_sort Module Subroutine
9 statements
Source File
private pure module subroutine sp_sort(array, reverse)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: array(0:)
logical, intent(in), optional :: reverse
Calls
Source Code
      pure module subroutine sp_sort(array, reverse)
!! `sp_sort(array[, reverse])` sorts the input `ARRAY` of type `real(sp)`
!! using a hybrid sort based on the `introsort` of David Musser.
!! The algorithm is of order O(N Ln(N)) for all inputs.
!! Because it relies on `quicksort`, the coefficient of the O(N Ln(N))
!! behavior is small for random data compared to other sorting algorithms.
         implicit none
         real(sp), intent(inout)         :: array(0:)
         logical, intent(in), optional :: reverse
      end subroutine sp_sort
Call graph
sp_sort calls pic_optional, sp_decrease_sort, sp_increase_sort
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
sp_decrease_sort calls introsort
sp_increase_sort calls introsort