sum_matrix_dp – PIC
sum_matrix_dp Function
24 statements
Source File
private function sum_matrix_dp(matrix, threaded) result(res)
perform the total sum of all components of type dp in a matrix
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: matrix(:,:)
logical, intent(in), optional :: threaded
Return Value real(kind=dp)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: cols
integer(kind=default_int), private :: i
integer(kind=default_int), private :: ii
integer(kind=default_int), private :: j
integer(kind=default_int), private :: jj
integer(kind=default_int), private :: rows
logical, private :: use_threads
Source Code
   function sum_matrix_dp(matrix, threaded) result(res)
        !! perform the total sum of all components of type dp in a matrix
      real(dp), intent(in) :: matrix(:, :)
      logical, intent(in), optional :: threaded
      logical :: use_threads
      real(dp) :: res
      integer(default_int) :: cols, rows, i, j, ii, jj
      rows = size(matrix, 1)
      cols = size(matrix, 2)
      use_threads = pic_optional(threaded, use_threaded_default)
      res = 0_dp
      if (use_threads) then
         !$omp parallel do collapse(2) private(i,j,ii,jj) reduction(+: res)
         do jj = 1, cols, block_size
            do ii = 1, rows, block_size
               do j = jj, min(jj + block_size - 1, cols)
                  do i = ii, min(ii + block_size - 1, rows)
                     res = res + matrix(i, j)
                  end do
               end do
            end do
         end do
         !$omp end parallel do
      else
         res = sum(matrix)
      end if
   end function sum_matrix_dp
Call graph
sum_matrix_dp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
pic_sum calls sum_matrix_dp