sum_vector_int64 – PIC
sum_vector_int64 Function
16 statements
Source File
private function sum_vector_int64(vector, threaded) result(res)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: vector(:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int64)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
logical, private :: use_threads
Source Code
   function sum_vector_int64(vector, threaded) result(res)
      integer(int64), intent(in)  :: vector(:)
      logical, intent(in), optional :: threaded
      logical :: use_threads
      integer(int64) :: res
      integer(default_int) :: i
      res = 0_int64
      use_threads = pic_optional(threaded, use_threaded_default)
      if (use_threads) then
         !$omp parallel do private(i) collapse(1) reduction(+:res)
         do i = 1, size(vector, 1)
            res = res + vector(i)
         end do
         !$omp end parallel do
      else
         res = sum(vector)
      end if
   end function sum_vector_int64
Call graph
sum_vector_int64 calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
pic_sum calls sum_vector_int64