to_char_int64 – PIC
to_char_int64 Function
7 statements
Source File
private function to_char_int64(i) result(trimmed_str)
transform an int64 to a string
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: i
Return Value character(len=:), allocatable
Called by
Variables
Type Visibility Attributes Name Initial
character(len=50), private :: str
Source Code
   function to_char_int64(i) result(trimmed_str)
      !! transform an int64 to a string
      integer(kind=int64), intent(in) :: i
      character(len=50) :: str
      character(len=:), allocatable :: trimmed_str
      write (str, "(I0)") i  ! Convert integer to string without leading spaces
      trimmed_str = trim(str)
   end function to_char_int64
Call graph
to_char calls to_char_int64
flop_rate_report calls to_char
print_matrix_dp calls to_char
print_matrix_int32 calls to_char
print_matrix_int64 calls to_char
print_matrix_sp calls to_char
print_packed_matrix_dp calls to_char
print_packed_matrix_int32 calls to_char
print_packed_matrix_int64 calls to_char
print_packed_matrix_sp calls to_char
print_vector_dp calls to_char
print_vector_int32 calls to_char
print_vector_int64 calls to_char
print_vector_sp calls to_char
timer_print_time calls to_char
pic_print_array calls print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp
print_3d_tensor_dp calls pic_print_array
print_3d_tensor_int32 calls pic_print_array
print_3d_tensor_int64 calls pic_print_array
print_3d_tensor_sp calls pic_print_array