to_string_dp – PIC
to_string_dp Function
9 statements
Source File
private function to_string_dp(r) result(trimmed_str)
transform a real(dp) to a string
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: r
Return Value character(len=:), allocatable
Called by
Variables
Type Visibility Attributes Name Initial
character(len=32), private :: fmt
character(len=50), private :: str
Source Code
   function to_string_dp(r) result(trimmed_str)
      !! transform a real(dp) to a string
      real(kind=dp), intent(in) :: r
      character(len=50) :: str
      character(len=:), allocatable :: trimmed_str
      character(len=32) :: fmt
      !call write_with_precision(r, str)
      write (fmt, '(A,I0,A)') '(F0.', dp_precision, ')'
      write (str, fmt) r
      trimmed_str = trim(str)
   end function to_string_dp
Call graph
to_string calls to_string_dp
flop_rate_report calls to_string
timer_print_time calls to_string