to_string_sp – PIC
to_string_sp Function
9 statements
Source File
private function to_string_sp(r) result(trimmed_str)
transform a real(sp) to a string
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: r
Return Value character(len=:), allocatable
Called by
Variables
Type Visibility Attributes Name Initial
character(len=50), private :: str
character(len=32), private :: style
Source Code
   function to_string_sp(r) result(trimmed_str)
      !! transform a real(sp) to a string
      real(kind=sp), intent(in) :: r
      character(len=50) :: str
      character(len=:), allocatable :: trimmed_str
      character(len=32) :: style
      !call write_with_precision(r, str)
      write (style, '(A,I0,A)') '(F0.', dp_precision, ')'
      write (str, style) r
      trimmed_str = trim(str)
   end function to_string_sp
Call graph
to_string calls to_string_sp
flop_rate_report calls to_string
print_matrix_dp calls to_string
print_matrix_int32 calls to_string
print_matrix_int64 calls to_string
print_matrix_sp calls to_string
print_packed_matrix_dp calls to_string
print_packed_matrix_int32 calls to_string
print_packed_matrix_int64 calls to_string
print_packed_matrix_sp calls to_string
print_vector_dp calls to_string
print_vector_int32 calls to_string
print_vector_int64 calls to_string
print_vector_sp calls to_string
timer_print_time calls to_string
pic_print_array calls print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp
print_3d_tensor_dp calls pic_print_array
print_3d_tensor_int32 calls pic_print_array
print_3d_tensor_int64 calls pic_print_array
print_3d_tensor_sp calls pic_print_array