to_string_r_sp – PIC
to_string_r_sp Module Function
13 statements
Source File
pure module function to_string_r_sp(value, format) result(string)
Format or transfer a real(sp) scalar as a string.
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: value
character(len=*), intent(in), optional :: format
Return Value character(len=:), allocatable
Calls
Variables
Type Visibility Attributes Name Initial
character(len=buffer_len), private :: buffer
integer, private :: stat
Source Code
   pure module function to_string_r_sp(value, format) result(string)
      real(sp), intent(in) :: value
      character(len=*), intent(in), optional :: format
      character(len=:), allocatable :: string
      character(len=buffer_len) :: buffer
      integer :: stat
      write (buffer, '('//pic_optional(format, "g0")//')', iostat=stat) value
      if (stat == 0) then
         string = trim(buffer)
      else
         string = err_sym
      end if
   end function to_string_r_sp
Call graph
to_string_r_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp