variance_dp – PIC
variance_dp Function
22 statements
Source File
private pure function variance_dp(array, sample) result(v)
Variance of a real(dp) array (core implementation, two-pass).
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
logical, intent(in), optional :: sample
Return Value real(kind=dp)
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: denom
real(kind=dp), private :: m
integer(kind=default_int), private :: n
logical, private :: use_sample
Source Code
   pure function variance_dp(array, sample) result(v)
      !! Variance of a real(dp) array (core implementation, two-pass).
      real(dp), intent(in) :: array(:)
      logical, intent(in), optional :: sample
      real(dp) :: v
      real(dp) :: m
      integer(default_int) :: n, denom
      logical :: use_sample
      use_sample = .true.
      if (present(sample)) use_sample = sample
      n = size(array, kind=default_int)
      if (use_sample) then
         denom = n - 1
      else
         denom = n
      end if
      if (denom <= 0) then
         v = 0.0_dp
      else
         m = sum(array)/real(n, dp)
         v = sum((array - m)**2)/real(denom, dp)
      end if
   end function variance_dp
Call graph
variance calls variance_dp, variance_int32, variance_int64, variance_sp
std_dev_dp calls variance_dp
std_dev_int32 calls variance_dp
std_dev_int64 calls variance_dp
std_dev_sp calls variance_dp
variance_int32 calls variance_dp
variance_int64 calls variance_dp
variance_sp calls variance_dp
std_dev calls std_dev_dp, std_dev_int32, std_dev_int64, std_dev_sp