write_unformatted – PIC
write_unformatted Subroutine
10 statements
Source File
private subroutine write_unformatted(string, unit, iostat, iomsg)
Write the character sequence hold by the string to a connected unformatted unit.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: unit
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Called by
Source Code
subroutine write_unformatted(string, unit, iostat, iomsg)
   type(string_type), intent(in) :: string
   integer, intent(in) :: unit
   integer, intent(out) :: iostat
   character(len=*), intent(inout) :: iomsg
   write (unit, iostat=iostat, iomsg=iomsg) int(slen(string), long)
   if (iostat == 0) then
      write (unit, iostat=iostat, iomsg=iomsg) maybe(string)
   end if
end subroutine write_unformatted
Call graph
write_unformatted calls slen, maybe
slen calls len_string
write (unformatted) calls write_unformatted