zfill_char – PIC
zfill_char Function
6 statements
Source File
private pure function zfill_char(string, output_length) result(res)
Left pad the input string with zeros
Returns a new string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: output_length
Return Value character(kind=output_length), len=max)
Calls
Called by
Source Code
   pure function zfill_char(string, output_length) result(res)
      character(len=*), intent(in) :: string
      integer, intent(in) :: output_length
      character(len=max(len(string), output_length)) :: res
      res = padl(string, output_length, "0")
   end function zfill_char
Call graph
zfill_char calls padl
padl calls padl_char_default, padl_char_pad_with, padl_string_default, padl_string_pad_with
padl_char_default calls padl
padl_string_default calls padl
padl_string_pad_with calls padl
zfill calls zfill_char