zfill_string – PIC
zfill_string Function
6 statements
Source File
private pure function zfill_string(string, output_length) result(res)
Left pad the input string with zeros
Returns a new string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
Return Value type(string_type)
Calls
Called by
Source Code
   pure function zfill_string(string, output_length) result(res)
      type(string_type), intent(in) :: string
      integer, intent(in) :: output_length
      type(string_type) :: res
      res = string_type(padl(char(string), output_length, "0"))
   end function zfill_string
Call graph
zfill_string calls padl
padl calls padl_char_default, padl_char_pad_with, padl_string_default, padl_string_pad_with
padl_char_default calls padl
padl_string_default calls padl
padl_string_pad_with calls padl
zfill calls zfill_string