blas_axpy – PIC
blas_axpy Interface
42 statements
Source File
private interface blas_axpy
explicit interface for BLAS AXPY routines
Usage: call blas_axpy(n, alpha, x, incx, y, incy)
This is not a public interface, it is used internally by pic_axpy
Called by
Subroutines
private pure subroutine caxpy(n, alpha, x, incx, y, incy)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=sp), intent(in) :: alpha
complex(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
complex(kind=sp), intent(inout) :: y(*)
integer(kind=default_int), intent(in) :: incy
private pure subroutine daxpy(n, alpha, x, incx, y, incy)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=dp), intent(in) :: alpha
real(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
real(kind=dp), intent(inout) :: y(*)
integer(kind=default_int), intent(in) :: incy
private pure subroutine saxpy(n, alpha, x, incx, y, incy)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=sp), intent(in) :: alpha
real(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
real(kind=sp), intent(inout) :: y(*)
integer(kind=default_int), intent(in) :: incy
private pure subroutine zaxpy(n, alpha, x, incx, y, incy)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=dp), intent(in) :: alpha
complex(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
complex(kind=dp), intent(inout) :: y(*)
integer(kind=default_int), intent(in) :: incy
Call graph
pic_caxpy calls blas_axpy
pic_daxpy calls blas_axpy
pic_saxpy calls blas_axpy
pic_zaxpy calls blas_axpy
pic_axpy calls pic_caxpy, pic_daxpy, pic_saxpy, pic_zaxpy