blas_asum – PIC
blas_asum Interface
34 statements
Source File
private interface blas_asum
this is the interface for the BLAS ASUM routines, it will call SASUM, DASUM, SCASUM, DZASUM Usage: result = blas_asum(x, incx) where x is the input vector, incx is the increment.
This is not a public interface, it is used internally by pic_asum
Called by
Functions
private pure function dasum(n, x, incx) result(res_dasum)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value real(kind=dp)
private pure function dzasum(n, x, incx) result(res_dzasum)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value real(kind=dp)
private pure function sasum(n, x, incx) result(res_sasum)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value real(kind=sp)
private pure function scasum(n, x, incx) result(res_scasum)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value real(kind=sp)
Call graph
pic_dasum calls blas_asum
pic_dzasum calls blas_asum
pic_sasum calls blas_asum
pic_scasum calls blas_asum
pic_asum calls pic_dasum, pic_dzasum, pic_sasum, pic_scasum