blas_iamax – PIC
blas_iamax Interface
34 statements
Source File
private interface blas_iamax
explicit interface for BLAS IAMAX routines
Usage: idx = blas_iamax(x, incx)
This is not a public interface, it is used internally by pic_iamax
Called by
Functions
private pure function icamax(n, x, incx) result(idx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value integer(kind=default_int)
private pure function idamax(n, x, incx) result(idx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value integer(kind=default_int)
private pure function isamax(n, x, incx) result(idx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=sp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value integer(kind=default_int)
private pure function izamax(n, x, incx) result(idx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=dp), intent(in) :: x(*)
integer(kind=default_int), intent(in) :: incx
Return Value integer(kind=default_int)
Call graph
pic_icamax calls blas_iamax
pic_idamax calls blas_iamax
pic_isamax calls blas_iamax
pic_izamax calls blas_iamax
pic_iamax calls pic_icamax, pic_idamax, pic_isamax, pic_izamax