blas_scal – PIC
blas_scal Interface
34 statements
Source File
public interface blas_scal
explicit interface for BLAS SCAL routines
Called by
Subroutines
private pure subroutine cscal(n, alpha, x, incx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=sp), intent(in) :: alpha
complex(kind=sp), intent(inout) :: x(*)
integer(kind=default_int), intent(in) :: incx
private pure subroutine dscal(n, alpha, x, incx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=dp), intent(in) :: alpha
real(kind=dp), intent(inout) :: x(*)
integer(kind=default_int), intent(in) :: incx
private pure subroutine sscal(n, alpha, x, incx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
real(kind=sp), intent(in) :: alpha
real(kind=sp), intent(inout) :: x(*)
integer(kind=default_int), intent(in) :: incx
private pure subroutine zscal(n, alpha, x, incx)
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
complex(kind=dp), intent(in) :: alpha
complex(kind=dp), intent(inout) :: x(*)
integer(kind=default_int), intent(in) :: incx
Call graph
pic_cscal calls blas_scal
pic_dscal calls blas_scal
pic_sscal calls blas_scal
pic_zscal calls blas_scal
pic_scal calls pic_cscal, pic_dscal, pic_sscal, pic_zscal