copy – PIC
copy Interface
10 statements
Source File
public interface copy
copy provides a blas-less implementation of xcopy where x is (i,s,d) icopy, scopy, dcopy if you built pic with BLAS use the copy interface provided there, I will not beat BLAS copy is implemented for (int32, int64, sp, dp) for 1 and 2d arrays of the same types
Usage: call copy(destination, source, [optional] threaded)
This subroutine is threaded for performance purposes if threaded is set to .true.
Note
If this subroutine is called inside a omp threaded region it will run serially because of nested parallelism
Calls
Module Procedures
private subroutine copy_vector_int32(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: dest(:)
integer(kind=int32), intent(in) :: source(:)
logical, intent(in), optional :: threaded
private subroutine copy_vector_int64(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: dest(:)
integer(kind=int64), intent(in) :: source(:)
logical, intent(in), optional :: threaded
private subroutine copy_vector_sp(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: dest(:)
real(kind=sp), intent(in) :: source(:)
logical, intent(in), optional :: threaded
private subroutine copy_vector_dp(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: dest(:)
real(kind=dp), intent(in) :: source(:)
logical, intent(in), optional :: threaded
private subroutine copy_matrix_int32(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: dest(:,:)
integer(kind=int32), intent(in) :: source(:,:)
logical, intent(in), optional :: threaded
private subroutine copy_matrix_int64(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: dest(:,:)
integer(kind=int64), intent(in) :: source(:,:)
logical, intent(in), optional :: threaded
private subroutine copy_matrix_sp(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: dest(:,:)
real(kind=sp), intent(in) :: source(:,:)
logical, intent(in), optional :: threaded
private subroutine copy_matrix_dp(dest, source, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: dest(:,:)
real(kind=dp), intent(in) :: source(:,:)
logical, intent(in), optional :: threaded
Call graph
copy calls copy_matrix_dp, copy_matrix_int32, copy_matrix_int64, copy_matrix_sp, copy_vector_dp, copy_vector_int32, copy_vector_int64, copy_vector_sp
copy_matrix_dp calls pic_optional
copy_matrix_int32 calls pic_optional
copy_matrix_int64 calls pic_optional
copy_matrix_sp calls pic_optional
copy_vector_dp calls pic_optional
copy_vector_int32 calls pic_optional
copy_vector_int64 calls pic_optional
copy_vector_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp