count – PIC
count Interface
experimental
6 statements
Source File
public interface count
Returns the number of times substring ‘pattern’ has appeared in the input string ‘string’
Calls
Module Procedures
private elemental function count_string_string(string, pattern, consider_overlapping) result(res)
Returns the number of times substring ‘pattern’ has appeared in the input string ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: pattern
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function count_string_char(string, pattern, consider_overlapping) result(res)
Returns the number of times substring ‘pattern’ has appeared in the input string ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: pattern
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function count_char_string(string, pattern, consider_overlapping) result(res)
Returns the number of times substring ‘pattern’ has appeared in the input string ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: pattern
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function count_char_char(string, pattern, consider_overlapping) result(res)
Returns the number of times substring ‘pattern’ has appeared in the input string ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: pattern
logical, intent(in), optional :: consider_overlapping
Return Value integer
Call graph
count calls count_char_char, count_char_string, count_string_char, count_string_string
count_char_char calls pic_optional, compute_lps
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp