fill – PIC
fill Interface
10 statements
Source File
public interface fill
fill provides a generic interface to assing a value alpha of types (int32, int64, sp, dp) as defined in pic_types.F90 The inteface supports filling 1d and 2d arrays of the specified variables
Usage: call fill(array, value, [optional] threaded)
This subroutine is threaded for performance purposes if threaded is set to .true.
Note
If this subroutine is called inside a omp threaded region it will run serially because of nested parallelism
Calls
Module Procedures
private subroutine fill_vector_int32(vector, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: vector(:)
integer(kind=int32), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_vector_int64(vector, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: vector(:)
integer(kind=int64), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_vector_sp(vector, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: vector(:)
real(kind=sp), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_vector_dp(vector, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: vector(:)
real(kind=dp), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_matrix_int32(matrix, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: matrix(:,:)
integer(kind=int32), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_matrix_int64(matrix, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: matrix(:,:)
integer(kind=int64), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_matrix_sp(matrix, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: matrix(:,:)
real(kind=sp), intent(in) :: alpha
logical, intent(in), optional :: threaded
private subroutine fill_matrix_dp(matrix, alpha, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: matrix(:,:)
real(kind=dp), intent(in) :: alpha
logical, intent(in), optional :: threaded
Call graph
fill calls fill_matrix_dp, fill_matrix_int32, fill_matrix_int64, fill_matrix_sp, fill_vector_dp, fill_vector_int32, fill_vector_int64, fill_vector_sp
fill_matrix_dp calls pic_optional
fill_matrix_int32 calls pic_optional
fill_matrix_int64 calls pic_optional
fill_matrix_sp calls pic_optional
fill_vector_dp calls pic_optional
fill_vector_int32 calls pic_optional
fill_vector_int64 calls pic_optional
fill_vector_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp