find – PIC
find Interface
6 statements
Source File
public interface find
Finds the starting index of substring ‘pattern’ in the input ‘string’ Specifications
Version: experimental
Calls
Called by
Module Procedures
private elemental function find_string_string(string, pattern, occurrence, consider_overlapping) result(res)
Returns the starting index of the ‘occurrence’th occurrence of substring ‘pattern’ in input ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: pattern
integer, intent(in), optional :: occurrence
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function find_string_char(string, pattern, occurrence, consider_overlapping) result(res)
Returns the starting index of the ‘occurrence’th occurrence of substring ‘pattern’ in input ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: pattern
integer, intent(in), optional :: occurrence
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function find_char_string(string, pattern, occurrence, consider_overlapping) result(res)
Returns the starting index of the ‘occurrence’th occurrence of substring ‘pattern’ in input ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: pattern
integer, intent(in), optional :: occurrence
logical, intent(in), optional :: consider_overlapping
Return Value integer
private elemental function find_char_char(string, pattern, occurrence, consider_overlapping) result(res)
Returns the starting index of the ‘occurrence’th occurrence of substring ‘pattern’ in input ‘string’ Returns an integer
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: pattern
integer, intent(in), optional :: occurrence
logical, intent(in), optional :: consider_overlapping
Return Value integer
Call graph
find calls find_char_char, find_char_string, find_string_char, find_string_string
find_char_char calls pic_optional, compute_lps
find_char_string calls find
find_string_char calls find
find_string_string calls find
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp