fuck_my_array_up – PIC
fuck_my_array_up Interface
7 statements
Source File
public interface fuck_my_array_up
Calls
Module Procedures
private subroutine scramble_int32_array(array)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: array(:)
private subroutine scramble_int64_array(array)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: array(:)
private subroutine scramble_sp_array(array)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: array(:)
private subroutine scramble_dp_array(array)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array(:)
private subroutine scramble_character_array(array)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(:)
Call graph
fuck_my_array_up calls scramble_character_array, scramble_dp_array, scramble_int32_array, scramble_int64_array, scramble_sp_array