is_in_range – PIC
is_in_range Interface
6 statements
Source File
public interface is_in_range
Test whether a value lies within the inclusive range [lo, hi].
Returns .true. when lo <= x .and. x <= hi. Supported types are: integer(int32), integer(int64), real(sp), real(dp). Usage: flag = is_in_range(x, lo, hi)
Calls
Module Procedures
private elemental function is_in_range_int32(x, lo, hi) result(flag)
Inclusive range test for integer(int32).
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x
integer(kind=int32), intent(in) :: lo
integer(kind=int32), intent(in) :: hi
Return Value logical
private elemental function is_in_range_int64(x, lo, hi) result(flag)
Inclusive range test for integer(int64).
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: x
integer(kind=int64), intent(in) :: lo
integer(kind=int64), intent(in) :: hi
Return Value logical
private elemental function is_in_range_sp(x, lo, hi) result(flag)
Inclusive range test for real(sp).
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x
real(kind=sp), intent(in) :: lo
real(kind=sp), intent(in) :: hi
Return Value logical
private elemental function is_in_range_dp(x, lo, hi) result(flag)
Inclusive range test for real(dp).
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
real(kind=dp), intent(in) :: lo
real(kind=dp), intent(in) :: hi
Return Value logical
Call graph
is_in_range calls is_in_range_dp, is_in_range_int32, is_in_range_int64, is_in_range_sp