is_sorted – PIC
is_sorted Interface
7 statements
Source File
public interface is_sorted
is_sorted provides a simple way to checking if a 1d array is sorted it is implemented for int32, int64, sp, and dp datatypes. The default is to check if an array is sorted in ascending fashion.
Usage: result = is_sorted(array, [optional] ASCENDING/DESCENDING)
Calls
Module Procedures
private pure function is_sorted_int32(array, order) result(sorted)
check if a 1d array of type int32 is sorted
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
private pure function is_sorted_int64(array, order) result(sorted)
check if a 1d array of type int64 is sorted
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
private pure function is_sorted_sp(array, order) result(sorted)
check if a 1d array of type sp is sorted
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
private pure function is_sorted_dp(array, order) result(sorted)
check if a 1d array of type dp is sorted
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
private pure function is_sorted_char(array, order) result(sorted)
check if a 1d array of type char is sorted
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: array(:)
integer(kind=default_int), intent(in), optional :: order
Return Value logical
Call graph
is_sorted calls is_sorted_char, is_sorted_dp, is_sorted_int32, is_sorted_int64, is_sorted_sp
is_sorted_char calls pic_optional
is_sorted_dp calls pic_optional
is_sorted_int32 calls pic_optional
is_sorted_int64 calls pic_optional
is_sorted_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp