join – PIC
join Interface
experimental
4 statements
Source File
public interface join
Joins an array of strings into a single string. The chunks are separated with a space, or an optional user-defined separator.
Calls
Module Procedures
private pure function join_string(strings, separator)
Joins a list of strings with a separator (default: space). Returns a new string
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: strings(:)
character(len=*), intent(in), optional :: separator
Return Value type(string_type)
private pure function join_char(strings, separator) result(joined)
Joins a list of strings with a separator (default: space). Returns a new string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: strings(:)
character(len=*), intent(in), optional :: separator
Return Value character(len=:), allocatable
Call graph
join calls join_char, join_string
join_string calls move
move calls move_char_char, move_char_string, move_string_char, move_string_string