mean – PIC
mean Interface
6 statements
Source File
public interface mean
Arithmetic mean of a 1-D array, returned as real(dp).
Returns 0 for an empty array. Supported input types are: integer(int32), integer(int64), real(sp), real(dp). Usage: m = mean(array)
Calls
Module Procedures
private pure function mean_int32(array) result(m)
Mean of an integer(int32) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:)
Return Value real(kind=dp)
private pure function mean_int64(array) result(m)
Mean of an integer(int64) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
Return Value real(kind=dp)
private pure function mean_sp(array) result(m)
Mean of a real(sp) array.
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:)
Return Value real(kind=dp)
private pure function mean_dp(array) result(m)
Mean of a real(dp) array.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
Return Value real(kind=dp)
Call graph
mean calls mean_dp, mean_int32, mean_int64, mean_sp