min_max – PIC
min_max Interface
6 statements
Source File
public interface min_max
Minimum and maximum of a 1-D array in a single length-2 result.
Returns [minval(array), maxval(array)], preserving the input type. The result is undefined for an empty array. Supported types are: integer(int32), integer(int64), real(sp), real(dp). Usage: mm = min_max(array) ! mm(1) = min, mm(2) = max
Calls
Module Procedures
private pure function min_max_int32(array) result(mm)
Minimum and maximum of an integer(int32) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:)
Return Value integer(kind=int32), (2)
private pure function min_max_int64(array) result(mm)
Minimum and maximum of an integer(int64) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
Return Value integer(kind=int64), (2)
private pure function min_max_sp(array) result(mm)
Minimum and maximum of a real(sp) array.
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:)
Return Value real(kind=sp), (2)
private pure function min_max_dp(array) result(mm)
Minimum and maximum of a real(dp) array.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
Return Value real(kind=dp), (2)
Call graph
min_max calls min_max_dp, min_max_int32, min_max_int64, min_max_sp