move – PIC
move Interface
experimental
6 statements
Source File
public interface move
Moves the allocated character scalar from ‘from’ to ‘to’
Calls
Called by
Module Procedures
private elemental subroutine move_string_string(from, to)
Moves the allocated character scalar from ‘from’ to ‘to’ No output
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(inout), target :: from
type(string_type), intent(inout), target :: to
private pure subroutine move_string_char(from, to)
Moves the allocated character scalar from ‘from’ to ‘to’ No output
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(inout) :: from
character(len=:), intent(out), allocatable :: to
private pure subroutine move_char_string(from, to)
Moves the allocated character scalar from ‘from’ to ‘to’ No output
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(inout), allocatable :: from
type(string_type), intent(out) :: to
private pure subroutine move_char_char(from, to)
Moves the allocated character scalar from ‘from’ to ‘to’ No output
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(inout), allocatable :: from
character(len=:), intent(out), allocatable :: to
Call graph
move calls move_char_char, move_char_string, move_string_char, move_string_string
join_string calls move
join calls join_string