operator(//) – PIC
operator(//) Interface
5 statements
Source File
public interface operator(//)
Concatenate two character sequences, the left-hand side, the right-hand side or both character sequences can be represented by a string.
This operator is elemental and returns a scalar character value.
Calls
Module Procedures
private elemental function concat_string_string(lhs, rhs) result(string)
Concatenate two character sequences. In this version both character sequences are by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: lhs
type(string_type), intent(in) :: rhs
Return Value type(string_type)
private elemental function concat_string_char(lhs, rhs) result(string)
Concatenate two character sequences. In this version the left-hand side character sequences is by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: lhs
character(len=*), intent(in) :: rhs
Return Value type(string_type)
private elemental function concat_char_string(lhs, rhs) result(string)
Concatenate two character sequences. In this version the right-hand side character sequences is by a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: lhs
type(string_type), intent(in) :: rhs
Return Value type(string_type)
Call graph
operator(SLASHSLASH) calls concat_char_string, concat_string_char, concat_string_string
concat_char_string calls maybe
concat_string_char calls maybe
concat_string_string calls maybe