pic_scramble_array – PIC
pic_scramble_array Interface
7 statements
Source File
public interface pic_scramble_array
Calls
Module Procedures
private subroutine scramble_array_int32(array)
should not be used, intended for testing purposes. randomizes an array of type int32
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: array(:)
private subroutine scramble_array_int64(array)
should not be used, intended for testing purposes. randomizes an array of type int64
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(inout) :: array(:)
private subroutine scramble_array_sp(array)
should not be used, intended for testing purposes. randomizes an array of type sp
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: array(:)
private subroutine scramble_array_dp(array)
should not be used, intended for testing purposes. randomizes an array of type dp
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: array(:)
private subroutine scramble_array_character(array)
should not be used, intended for testing purposes. randomizes an array of type char
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: array(:)
Call graph
pic_scramble_array calls scramble_array_character, scramble_array_dp, scramble_array_int32, scramble_array_int64, scramble_array_sp