pic_print_array – PIC
pic_print_array Interface
18 statements
Source File
public interface pic_print_array
Generic interface for printing arrays of different types
Usage: call print_array_v2(array, [optional] format) Where format can be: NUMPY, PLAIN, MATHEMATICA (can use lower caps)
Implemented types are:
array(:) -> int32, int64, sp, dp
array(:,:) -> int32, int64, sp, dp
array(:) (packed matrix) -> sp, dp
array(:,:,:) -> sp, dp
Calls
Called by
Module Procedures
private subroutine print_vector_int32(vector, format_type)
print a vector of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: vector(:)
character(len=*), intent(in), optional :: format_type
private subroutine print_vector_int64(vector, format_type)
print a vector of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: vector(:)
character(len=*), intent(in), optional :: format_type
private subroutine print_vector_sp(vector, format_type)
print a vector of values
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: vector(:)
character(len=*), intent(in), optional :: format_type
private subroutine print_vector_dp(vector, format_type)
print a vector of values
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vector(:)
character(len=*), intent(in), optional :: format_type
private subroutine print_matrix_int32(matrix, format_type)
print a matrix of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: matrix(:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_matrix_int64(matrix, format_type)
print a matrix of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: matrix(:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_matrix_sp(matrix, format_type)
print a matrix of values
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: matrix(:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_matrix_dp(matrix, format_type)
print a matrix of values
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: matrix(:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_packed_matrix_int32(packed, n_elements, format_type)
Print a packed lower triangular matrix of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: packed(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
private subroutine print_packed_matrix_int64(packed, n_elements, format_type)
Print a packed lower triangular matrix of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: packed(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
private subroutine print_packed_matrix_sp(packed, n_elements, format_type)
Print a packed lower triangular matrix of values
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: packed(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
private subroutine print_packed_matrix_dp(packed, n_elements, format_type)
Print a packed lower triangular matrix of values
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: packed(:)
integer(kind=default_int), intent(in) :: n_elements
character(len=*), intent(in), optional :: format_type
private subroutine print_3d_tensor_int32(matrix, format_type)
Print a 3D tensor of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: matrix(:,:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_3d_tensor_int64(matrix, format_type)
Print a 3D tensor of values
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: matrix(:,:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_3d_tensor_sp(matrix, format_type)
Print a 3D tensor of values
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: matrix(:,:,:)
character(len=*), intent(in), optional :: format_type
private subroutine print_3d_tensor_dp(matrix, format_type)
Print a 3D tensor of values
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: matrix(:,:,:)
character(len=*), intent(in), optional :: format_type
Call graph
pic_print_array calls print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp, print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp
print_3d_tensor_dp calls pic_print_array, pic_optional, set_brackets
print_3d_tensor_int32 calls pic_print_array, pic_optional, set_brackets
print_3d_tensor_int64 calls pic_print_array, pic_optional, set_brackets
print_3d_tensor_sp calls pic_print_array, pic_optional, set_brackets
print_matrix_dp calls pic_optional, to_string, set_brackets
print_matrix_int32 calls pic_optional, to_string, set_brackets
print_matrix_int64 calls pic_optional, to_string, set_brackets
print_matrix_sp calls pic_optional, to_string, set_brackets
print_packed_matrix_dp calls pic_optional, to_string, set_brackets
print_packed_matrix_int32 calls pic_optional, to_string, set_brackets
print_packed_matrix_int64 calls pic_optional, to_string, set_brackets
print_packed_matrix_sp calls pic_optional, to_string, set_brackets
print_vector_dp calls pic_optional, to_string, set_brackets
print_vector_int32 calls pic_optional, to_string, set_brackets
print_vector_int64 calls pic_optional, to_string, set_brackets
print_vector_sp calls pic_optional, to_string, set_brackets
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp
set_brackets calls to_upper