pic_iamax – PIC
pic_iamax Interface
4 statements
Source File
public interface pic_iamax
general interface of the BLAS IAMAX routines, will call ISAMAX, IDAMAX, ICAMAX, IZAMAX
Usage: idx = pic_iamax(x, incx)
where x is the input vector, incx is the increment. The vector x must be an allocatable array, we deduce the shape from it. The increment incx is 1 by default.
Calls
Module Procedures
private function pic_isamax(x) result(idx)
interface for single precision index of maximum absolute value
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
Return Value integer(kind=default_int)
private function pic_idamax(x) result(idx)
interface for double precision index of maximum absolute value
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
Return Value integer(kind=default_int)
Call graph
pic_iamax calls pic_idamax, pic_isamax
pic_idamax calls blas_iamax
pic_isamax calls blas_iamax