pic_dot – PIC
pic_dot Interface
6 statements
Source File
public interface pic_dot
general interface of the BLAS DOT routines, will call SDOT, DDOT, CDOTC, ZDOTC
Usage: result = pic_dot(x, y)
where x is the input vector, y is the output vector. The vectors x and y must be allocatable arrays, we deduce the shapes from them.
Calls
Module Procedures
private function pic_sdot(x, y) result(res)
interface for single precision dot product
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
real(kind=sp), intent(in) :: y(:)
Return Value real(kind=sp)
private function pic_ddot(x, y) result(res)
interface for double precision dot product
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
real(kind=dp), intent(in) :: y(:)
Return Value real(kind=dp)
private function pic_cdotc(x, y) result(res)
interface for single precision complex dot product
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
complex(kind=sp), intent(in) :: y(:)
Return Value complex(kind=sp)
private function pic_zdotc(x, y) result(res)
interface for double precision complex dot product
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
complex(kind=dp), intent(in) :: y(:)
Return Value complex(kind=dp)
Call graph
pic_dot calls pic_cdotc, pic_ddot, pic_sdot, pic_zdotc
pic_cdotc calls blas_dot
pic_ddot calls blas_dot
pic_sdot calls blas_dot
pic_zdotc calls blas_dot