pic_asum – PIC
pic_asum Interface
6 statements
Source File
public interface pic_asum
general interface of the BLAS ASUM routines, will call SASUM, DASUM, SCASUM, DZASUM
Usage: result = pic_asum(x, incx)
where x is a vector and incx is the increment, this will return the sum of the absolute values of the elements of x.
The vector x must be an allocatable array, we deduce the shape from it. The increment incx is 1 by default.
Calls
Module Procedures
private function pic_sasum(x) result(res)
interface for single precision absolute sum
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: x(:)
Return Value real(kind=sp)
private function pic_dasum(x) result(res)
interface for double precision absolute sum
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x(:)
Return Value real(kind=dp)
private function pic_scasum(x) result(res)
interface for single precision complex absolute sum
Arguments
Type Intent Optional Attributes Name
complex(kind=sp), intent(in) :: x(:)
Return Value real(kind=sp)
private function pic_dzasum(x) result(res)
interface for double precision complex absolute sum
Arguments
Type Intent Optional Attributes Name
complex(kind=dp), intent(in) :: x(:)
Return Value real(kind=dp)
Call graph
pic_asum calls pic_dasum, pic_dzasum, pic_sasum, pic_scasum
pic_dasum calls blas_asum
pic_dzasum calls blas_asum
pic_sasum calls blas_asum
pic_scasum calls blas_asum