pic_sum – PIC
pic_sum Interface
14 statements
Source File
public interface pic_sum
pic_sum provides a threaded alternative to the sum(array) Fortran intrinsic which will be too slow for large sizes of vectors and matrices. Note that this provides the total sum. As opposed to the blas alternative XASUM which does the absolute sum
pic_sum is implemented for (int32, int64, sp, dp) 1 and 2d arrays
Usage: result = pic_sum(array, [optional] threaded)
This subroutine is threaded for performance purposes if threaded is set to true
Calls
Module Procedures
private function sum_vector_int32(vector, threaded) result(res)
perform the total sum of all components of type int32 in a vector
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: vector(:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int32)
private function sum_vector_int64(vector, threaded) result(res)
perform the total sum of all components of type int64 in a vector
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: vector(:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int64)
private function sum_vector_sp(vector, threaded) result(res)
perform the total sum of all components of type sp in a vector
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: vector(:)
logical, intent(in), optional :: threaded
Return Value real(kind=sp)
private function sum_vector_dp(vector, threaded) result(res)
perform the total sum of all components of type dp in a vector
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vector(:)
logical, intent(in), optional :: threaded
Return Value real(kind=dp)
private function sum_matrix_int32(matrix, threaded) result(res)
perform the total sum of all components of type int32 in a matrix
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: matrix(:,:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int32)
private function sum_matrix_int64(matrix, threaded) result(res)
perform the total sum of all components of type int64 in a matrix
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: matrix(:,:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int64)
private function sum_matrix_sp(matrix, threaded) result(res)
perform the total sum of all components of type sp in a matrix
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: matrix(:,:)
logical, intent(in), optional :: threaded
Return Value real(kind=sp)
private function sum_matrix_dp(matrix, threaded) result(res)
perform the total sum of all components of type dp in a matrix
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: matrix(:,:)
logical, intent(in), optional :: threaded
Return Value real(kind=dp)
private function sum_3d_tensor_int32(tensor, threaded) result(res)
perform the total sum of all components of type int32 in a 3d tensor
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: tensor(:,:,:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int32)
private function sum_3d_tensor_int64(tensor, threaded) result(res)
perform the total sum of all components of type int64 in a 3d tensor
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: tensor(:,:,:)
logical, intent(in), optional :: threaded
Return Value integer(kind=int64)
private function sum_3d_tensor_sp(tensor, threaded) result(res)
perform the total sum of all components of type sp in a 3d tensor
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: tensor(:,:,:)
logical, intent(in), optional :: threaded
Return Value real(kind=sp)
private function sum_3d_tensor_dp(tensor, threaded) result(res)
perform the total sum of all components of type dp in a 3d tensor
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: tensor(:,:,:)
logical, intent(in), optional :: threaded
Return Value real(kind=dp)
Call graph
pic_sum calls sum_3d_tensor_dp, sum_3d_tensor_int32, sum_3d_tensor_int64, sum_3d_tensor_sp, sum_matrix_dp, sum_matrix_int32, sum_matrix_int64, sum_matrix_sp, sum_vector_dp, sum_vector_int32, sum_vector_int64, sum_vector_sp
sum_3d_tensor_dp calls pic_optional
sum_3d_tensor_int32 calls pic_optional
sum_3d_tensor_int64 calls pic_optional
sum_3d_tensor_sp calls pic_optional
sum_matrix_dp calls pic_optional
sum_matrix_int32 calls pic_optional
sum_matrix_int64 calls pic_optional
sum_matrix_sp calls pic_optional
sum_vector_dp calls pic_optional
sum_vector_int32 calls pic_optional
sum_vector_int64 calls pic_optional
sum_vector_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp