pic_transpose – PIC
pic_transpose Interface
6 statements
Source File
public interface pic_transpose
pic_transpose provides a blas-less, threaded alternative to the Fortran transpose intrinsic which will be slow for large matrix sizes. pic_transpose does not assume symmetric matrices
pic_transpose is implemented for (int32, int64, sp, dp) 2d arrays
Usage: call pic_transpose(matrix_to_transpose, result, [optional] threaded)
This subroutine is threaded for performance purposes if threaded is set to true
Calls
Module Procedures
private subroutine transpose_matrix_int32(A, B, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: A(:,:)
integer(kind=int32), intent(out) :: B(:,:)
logical, intent(in), optional :: threaded
private subroutine transpose_matrix_int64(A, B, threaded)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: A(:,:)
integer(kind=int64), intent(out) :: B(:,:)
logical, intent(in), optional :: threaded
private subroutine transpose_matrix_sp(A, B, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: A(:,:)
real(kind=sp), intent(out) :: B(:,:)
logical, intent(in), optional :: threaded
private subroutine transpose_matrix_dp(A, B, threaded)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
real(kind=dp), intent(out) :: B(:,:)
logical, intent(in), optional :: threaded
Call graph
pic_transpose calls transpose_matrix_dp, transpose_matrix_int32, transpose_matrix_int64, transpose_matrix_sp
transpose_matrix_dp calls pic_optional
transpose_matrix_int32 calls pic_optional
transpose_matrix_int64 calls pic_optional
transpose_matrix_sp calls pic_optional
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp