scan – PIC
scan Interface
5 statements
Source File
public interface scan
Scan a string for the presence of a set of characters. Scans a string for any of the characters in a set of characters.
If back is either absent or false, this function returns the position of the leftmost character of string that is in set. If back is true, the rightmost position is returned. If no character of set is found in string, the result is zero.
This method is elemental and returns a default integer scalar value.
Calls
Module Procedures
private elemental function scan_string_string(string, set, back) result(pos)
Scan a character sequence for any of the characters in a set of characters. In this version both the character sequence and the character set are represented by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function scan_string_char(string, set, back) result(pos)
Scan a character sequence for any of the characters in a set of characters. In this version the character sequences is represented by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function scan_char_string(string, set, back) result(pos)
Scan a character sequence for any of the characters in a set of characters. In this version the set of characters is represented by a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
Call graph
scan calls scan_char_string, scan_string_char, scan_string_string
scan_char_string calls pic_optional, maybe
scan_string_char calls pic_optional, maybe
scan_string_string calls pic_optional, maybe
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp