to_string – PIC
to_string Interface
16 statements
Source File
public interface to_string
converts a variable of type (int32, int64, sp, dp, char, logical) to a “string” which is just a collecting of chars.
Usage result = to_string(variable)
Note
the functions here are not elemental so they won’t work for arrays. Please use pic_print_array_v2 module for this
Calls
Called by
Module Procedures
private function to_string_int32(i) result(trimmed_str)
transform an int32 to a string
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: i
Return Value character(len=:), allocatable
private function to_string_int64(i) result(trimmed_str)
transform an int64 to a string
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: i
Return Value character(len=:), allocatable
private function to_string_sp(r) result(trimmed_str)
transform a real(sp) to a string
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: r
Return Value character(len=:), allocatable
private function to_string_dp(r) result(trimmed_str)
transform a real(dp) to a string
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: r
Return Value character(len=:), allocatable
private function to_string_char(c) result(trimmed_str)
transform a character to a string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: c
Return Value character(len=:), allocatable
private function to_string_logical(l) result(trimmed_str)
tranform a logical to a string either true or false
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: l
Return Value character(len=:), allocatable
private function to_string_vector_int32(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:)
Return Value character(len=:), allocatable
private function to_string_vector_int64(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
Return Value character(len=:), allocatable
private function to_string_vector_sp(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:)
Return Value character(len=:), allocatable
private function to_string_vector_dp(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
Return Value character(len=:), allocatable
private function to_string_matrix_int32(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:,:)
Return Value character(len=:), allocatable
private function to_string_matrix_int64(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:,:)
Return Value character(len=:), allocatable
private function to_string_matrix_sp(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:,:)
Return Value character(len=:), allocatable
private function to_string_matrix_dp(array) result(trimmed_str)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:,:)
Return Value character(len=:), allocatable
Call graph
to_string calls to_string_char, to_string_dp, to_string_int32, to_string_int64, to_string_logical, to_string_matrix_dp, to_string_matrix_int32, to_string_matrix_int64, to_string_matrix_sp, to_string_sp, to_string_vector_dp, to_string_vector_int32, to_string_vector_int64, to_string_vector_sp
flop_rate_report calls to_string
print_matrix_dp calls to_string
print_matrix_int32 calls to_string
print_matrix_int64 calls to_string
print_matrix_sp calls to_string
print_packed_matrix_dp calls to_string
print_packed_matrix_int32 calls to_string
print_packed_matrix_int64 calls to_string
print_packed_matrix_sp calls to_string
print_vector_dp calls to_string
print_vector_int32 calls to_string
print_vector_int64 calls to_string
print_vector_sp calls to_string
timer_print_time calls to_string
pic_print_array calls print_matrix_dp, print_matrix_int32, print_matrix_int64, print_matrix_sp, print_packed_matrix_dp, print_packed_matrix_int32, print_packed_matrix_int64, print_packed_matrix_sp, print_vector_dp, print_vector_int32, print_vector_int64, print_vector_sp, print_3d_tensor_dp, print_3d_tensor_int32, print_3d_tensor_int64, print_3d_tensor_sp
print_3d_tensor_dp calls pic_print_array
print_3d_tensor_int32 calls pic_print_array
print_3d_tensor_int64 calls pic_print_array
print_3d_tensor_sp calls pic_print_array