variance – PIC
variance Interface
6 statements
Source File
public interface variance
Variance of a 1-D array, returned as real(dp).
By default the unbiased sample variance (dividing by n - 1) is returned; pass sample = .false. for the population variance (dividing by n). Returns 0 when there are too few elements to define it. Supported input types are: integer(int32), integer(int64), real(sp), real(dp). Usage: v = variance(array [, sample])
Calls
Module Procedures
private pure function variance_int32(array, sample) result(v)
Variance of an integer(int32) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: array(:)
logical, intent(in), optional :: sample
Return Value real(kind=dp)
private pure function variance_int64(array, sample) result(v)
Variance of an integer(int64) array.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: array(:)
logical, intent(in), optional :: sample
Return Value real(kind=dp)
private pure function variance_sp(array, sample) result(v)
Variance of a real(sp) array.
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(in) :: array(:)
logical, intent(in), optional :: sample
Return Value real(kind=dp)
private pure function variance_dp(array, sample) result(v)
Variance of a real(dp) array (core implementation, two-pass).
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: array(:)
logical, intent(in), optional :: sample
Return Value real(kind=dp)
Call graph
variance calls variance_dp, variance_int32, variance_int64, variance_sp
variance_int32 calls variance_dp
variance_int64 calls variance_dp
variance_sp calls variance_dp