verify – PIC
verify Interface
5 statements
Source File
public interface verify
Scan a string for the absence of a set of characters. Verifies that all the characters in string belong to the set of characters in set.
If back is either absent or false, this function returns the position of the leftmost character of string that is not in set. If back is true, the rightmost position is returned. If all characters of string are found in set, the result is zero.
This method is elemental and returns a default integer scalar value.
Calls
Module Procedures
private elemental function verify_string_string(string, set, back) result(pos)
Verify a character sequence for the absence any of the characters in a set of characters. In this version both the character sequence and the character set are represented by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
type(string_type), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function verify_string_char(string, set, back) result(pos)
Verify a character sequence for the absence any of the characters in a set of characters. In this version the character sequences is represented by a string.
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
character(len=*), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
private elemental function verify_char_string(string, set, back) result(pos)
Verify a character sequence for the absence any of the characters in a set of characters. In this version the set of characters is represented by a string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(string_type), intent(in) :: set
logical, intent(in), optional :: back
Return Value integer
Call graph
verify calls verify_char_string, verify_string_char, verify_string_string
verify_char_string calls pic_optional, maybe
verify_string_char calls pic_optional, maybe
verify_string_string calls pic_optional, maybe
pic_optional calls optional_char, optional_dp, optional_int32, optional_int64, optional_logical, optional_sp