zfill – PIC
zfill Interface
experimental
4 statements
Source File
public interface zfill
Left pad the input string with zeros.
Calls
Module Procedures
private pure function zfill_string(string, output_length) result(res)
Left pad the input string with zeros
Read more…
Arguments
Type Intent Optional Attributes Name
type(string_type), intent(in) :: string
integer, intent(in) :: output_length
Return Value type(string_type)
private pure function zfill_char(string, output_length) result(res)
Left pad the input string with zeros
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: output_length
Return Value character(kind=output_length), len=max)
Call graph
zfill calls zfill_char, zfill_string
zfill_char calls padl
zfill_string calls padl
padl calls padl_char_default, padl_char_pad_with, padl_string_default, padl_string_pad_with
padl_char_default calls padl
padl_string_default calls padl
padl_string_pad_with calls padl