# CMake generated Testfile for 
# Source directory: /home/runner/work/pic/pic/test
# Build directory: /home/runner/work/pic/pic/build_default/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[pic/base_utils]=] "pic-tester" "base_utils")
set_tests_properties([=[pic/base_utils]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string]=] "pic-tester" "pic_string")
set_tests_properties([=[pic/pic_string]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_assignment]=] "pic-tester" "pic_string_assignment")
set_tests_properties([=[pic/pic_string_assignment]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_functions]=] "pic-tester" "pic_string_functions")
set_tests_properties([=[pic/pic_string_functions]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_intrinsic]=] "pic-tester" "pic_string_intrinsic")
set_tests_properties([=[pic/pic_string_intrinsic]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_match]=] "pic-tester" "pic_string_match")
set_tests_properties([=[pic/pic_string_match]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_operator]=] "pic-tester" "pic_string_operator")
set_tests_properties([=[pic/pic_string_operator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_strip_chomp]=] "pic-tester" "pic_string_strip_chomp")
set_tests_properties([=[pic/pic_string_strip_chomp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_to_string]=] "pic-tester" "pic_string_to_string")
set_tests_properties([=[pic/pic_string_to_string]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_ascii]=] "pic-tester" "pic_ascii")
set_tests_properties([=[pic/pic_ascii]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_timers]=] "pic-tester" "pic_timers")
set_tests_properties([=[pic/pic_timers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_logger]=] "pic-tester" "pic_logger")
set_tests_properties([=[pic/pic_logger]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_flop_recorder]=] "pic-tester" "pic_flop_recorder")
set_tests_properties([=[pic/pic_flop_recorder]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_flop_rate]=] "pic-tester" "pic_flop_rate")
set_tests_properties([=[pic/pic_flop_rate]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_matrix_printer_v2]=] "pic-tester" "pic_matrix_printer_v2")
set_tests_properties([=[pic/pic_matrix_printer_v2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_array]=] "pic-tester" "pic_array")
set_tests_properties([=[pic/pic_array]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_optional]=] "pic-tester" "pic_optional")
set_tests_properties([=[pic/pic_optional]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_hash]=] "pic-tester" "pic_hash")
set_tests_properties([=[pic/pic_hash]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_sorting]=] "pic-tester" "pic_sorting")
set_tests_properties([=[pic/pic_sorting]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_pure_logger]=] "pic-tester" "pic_pure_logger")
set_tests_properties([=[pic/pic_pure_logger]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_error]=] "pic-tester" "pic_error")
set_tests_properties([=[pic/pic_error]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_profiler]=] "pic-tester" "pic_profiler")
set_tests_properties([=[pic/pic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
add_test([=[pic/pic_string_derivedtype_io]=] "pic-tester" "pic_string_derivedtype_io")
set_tests_properties([=[pic/pic_string_derivedtype_io]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/pic/pic/test/CMakeLists.txt;55;add_test;/home/runner/work/pic/pic/test/CMakeLists.txt;0;")
