function(print_pic_summary)
  message(STATUS "")
  message(STATUS "========== PIC Configuration Summary ==========")
  message(STATUS "  PIC_DEFAULT_INT8      : ${PIC_DEFAULT_INT8}")
  message(STATUS "  PIC_ENABLE_MPI        : ${PIC_ENABLE_MPI}")
  message(STATUS "  PIC_ENABLE_OMP        : ${PIC_ENABLE_OMP}")
  message(STATUS "  PIC_ENABLE_BLAS       : ${PIC_ENABLE_BLAS}")
  message(STATUS "  PIC_ENABLE_TESTING    : ${PIC_ENABLE_TESTING}")
  message(STATUS "  PIC_ENABLE_JONQUIL    : ${PIC_ENABLE_JONQUIL}")
  message(STATUS "===============================================")
endfunction()
