function(print_pic_summary)
  message(STATUS "")
  message(STATUS "========== PIC Configuration Summary ==========")
  message(STATUS "  Fortran compiler      : ${CMAKE_Fortran_COMPILER_ID}")
  message(STATUS "  PIC_DEFAULT_INT8      : ${PIC_DEFAULT_INT8}")
  message(STATUS "  PIC_ENABLE_OMP        : ${PIC_ENABLE_OMP}")
  message(STATUS "  PIC_ENABLE_TESTING    : ${PIC_ENABLE_TESTING}")
  message(STATUS "  PIC_ENABLE_JONQUIL    : ${PIC_ENABLE_JONQUIL}")
  message(STATUS "===============================================")
endfunction()
