function(print_pic_summary)
  message(STATUS "")
  message(STATUS "========== PIC Configuration Summary ==========")
  message(STATUS "  Fortran compiler      : ${CMAKE_Fortran_COMPILER_ID}")
  message(STATUS "  PIC_DEFAULT_INT8      : ${PIC_DEFAULT_INT8}")
  message(STATUS "  PIC_ENABLE_OMP        : ${PIC_ENABLE_OMP}")
  message(STATUS "  PIC_ENABLE_TESTING    : ${PIC_ENABLE_TESTING}")
  message(STATUS "  PIC_DISABLE_PROFILER  : ${PIC_DISABLE_PROFILER}")
  message(STATUS "  PIC_USE_NVTX          : ${PIC_USE_NVTX}")
  message(STATUS "  PIC_USE_C_DATATYPES   : ${PIC_USE_C_DATATYPES}")
  message(STATUS "===============================================")
endfunction()
