name: Deploy FORD docs

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install FORD
        run: pip install ford

      - name: Pip install graphviz
        run: pip install graphviz==0.20.1

      - name: Install c++ graphviz backend
        run: sudo apt install graphviz

      - name: Build FORD docs
        run: ford -m "PIC_HAVE_BLAS" ford.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/fpm-ford
          publish_branch: gh-pages-docs
